platform:ios, '8.0'
inhibit_all_warnings!
def pods
pod 'AFNetworking'
pod 'MJExtension'
pod 'FMDB'
pod 'Masonry'
pod 'pop'
pod 'IQKeyboardManager'
pod 'XMPPFramework'
pod 'UITableView+FDTemplateLayoutCell'
pod 'ProtocolBuffers'
pod 'JSPatch'
pod 'iRate'
pod 'iVersion'
pod 'JPFPSStatus'
pod 'UMengAnalytics-NO-IDFA'
pod 'GYKit' , :git => 'http://git.gyist.com/ios/GYKit.git', :tag => '1.0.3'
end
target 'GYRestaurant' do
  pods
end