// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "ImHxcommon.pb.h"
// @@protoc_insertion_point(imports)

@class AddFriendReq;
@class AddFriendReqBuilder;
@class AddFriendRsp;
@class AddFriendRspBuilder;
@class DelFriendReq;
@class DelFriendReqBuilder;
@class DelFriendRsp;
@class DelFriendRspBuilder;
@class ModifyFriendReq;
@class ModifyFriendReqBuilder;
@class ModifyFriendRsp;
@class ModifyFriendRspBuilder;
@class ShieldFriendReq;
@class ShieldFriendReqBuilder;
@class ShieldFriendRsp;
@class ShieldFriendRspBuilder;
@class VerifyFriendReq;
@class VerifyFriendReqBuilder;
@class VerifyFriendRsp;
@class VerifyFriendRspBuilder;



@interface ImHxfriendRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define AddFriendReq_user_id @"userId"
#define AddFriendReq_friend_id @"friendId"
#define AddFriendReq_content @"content"
#define AddFriendReq_verify @"verify"
@interface AddFriendReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  BOOL hasContent_:1;
  BOOL hasVerify_:1;
  NSString* userId;
  NSString* friendId;
  NSString* content;
  NSString* verify;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
- (BOOL) hasContent;
- (BOOL) hasVerify;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;
@property (readonly, strong) NSString* content;
@property (readonly, strong) NSString* verify;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AddFriendReqBuilder*) builder;
+ (AddFriendReqBuilder*) builder;
+ (AddFriendReqBuilder*) builderWithPrototype:(AddFriendReq*) prototype;
- (AddFriendReqBuilder*) toBuilder;

+ (AddFriendReq*) parseFromData:(NSData*) data;
+ (AddFriendReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddFriendReq*) parseFromInputStream:(NSInputStream*) input;
+ (AddFriendReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AddFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AddFriendReqBuilder : PBGeneratedMessageBuilder {
@private
  AddFriendReq* resultAddFriendReq;
}

- (AddFriendReq*) defaultInstance;

- (AddFriendReqBuilder*) clear;
- (AddFriendReqBuilder*) clone;

- (AddFriendReq*) build;
- (AddFriendReq*) buildPartial;

- (AddFriendReqBuilder*) mergeFrom:(AddFriendReq*) other;
- (AddFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AddFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (AddFriendReqBuilder*) setUserId:(NSString*) value;
- (AddFriendReqBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (AddFriendReqBuilder*) setFriendId:(NSString*) value;
- (AddFriendReqBuilder*) clearFriendId;

- (BOOL) hasContent;
- (NSString*) content;
- (AddFriendReqBuilder*) setContent:(NSString*) value;
- (AddFriendReqBuilder*) clearContent;

- (BOOL) hasVerify;
- (NSString*) verify;
- (AddFriendReqBuilder*) setVerify:(NSString*) value;
- (AddFriendReqBuilder*) clearVerify;
@end

#define AddFriendRsp_user_id @"userId"
#define AddFriendRsp_friend_id @"friendId"
#define AddFriendRsp_result_code @"resultCode"
@interface AddFriendRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  BOOL hasResultCode_:1;
  NSString* userId;
  NSString* friendId;
  ResultCode resultCode;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
- (BOOL) hasResultCode;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;
@property (readonly) ResultCode resultCode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AddFriendRspBuilder*) builder;
+ (AddFriendRspBuilder*) builder;
+ (AddFriendRspBuilder*) builderWithPrototype:(AddFriendRsp*) prototype;
- (AddFriendRspBuilder*) toBuilder;

+ (AddFriendRsp*) parseFromData:(NSData*) data;
+ (AddFriendRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddFriendRsp*) parseFromInputStream:(NSInputStream*) input;
+ (AddFriendRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AddFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AddFriendRspBuilder : PBGeneratedMessageBuilder {
@private
  AddFriendRsp* resultAddFriendRsp;
}

- (AddFriendRsp*) defaultInstance;

- (AddFriendRspBuilder*) clear;
- (AddFriendRspBuilder*) clone;

- (AddFriendRsp*) build;
- (AddFriendRsp*) buildPartial;

- (AddFriendRspBuilder*) mergeFrom:(AddFriendRsp*) other;
- (AddFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AddFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (AddFriendRspBuilder*) setUserId:(NSString*) value;
- (AddFriendRspBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (AddFriendRspBuilder*) setFriendId:(NSString*) value;
- (AddFriendRspBuilder*) clearFriendId;

- (BOOL) hasResultCode;
- (ResultCode) resultCode;
- (AddFriendRspBuilder*) setResultCode:(ResultCode) value;
- (AddFriendRspBuilder*) clearResultCode;
@end

#define VerifyFriendReq_user_id @"userId"
#define VerifyFriendReq_friend_id @"friendId"
#define VerifyFriendReq_agree @"agree"
#define VerifyFriendReq_content @"content"
@interface VerifyFriendReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAgree_:1;
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  BOOL hasContent_:1;
  SInt32 agree;
  NSString* userId;
  NSString* friendId;
  NSString* content;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
- (BOOL) hasAgree;
- (BOOL) hasContent;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;
@property (readonly) SInt32 agree;
@property (readonly, strong) NSString* content;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (VerifyFriendReqBuilder*) builder;
+ (VerifyFriendReqBuilder*) builder;
+ (VerifyFriendReqBuilder*) builderWithPrototype:(VerifyFriendReq*) prototype;
- (VerifyFriendReqBuilder*) toBuilder;

+ (VerifyFriendReq*) parseFromData:(NSData*) data;
+ (VerifyFriendReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VerifyFriendReq*) parseFromInputStream:(NSInputStream*) input;
+ (VerifyFriendReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VerifyFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (VerifyFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface VerifyFriendReqBuilder : PBGeneratedMessageBuilder {
@private
  VerifyFriendReq* resultVerifyFriendReq;
}

- (VerifyFriendReq*) defaultInstance;

- (VerifyFriendReqBuilder*) clear;
- (VerifyFriendReqBuilder*) clone;

- (VerifyFriendReq*) build;
- (VerifyFriendReq*) buildPartial;

- (VerifyFriendReqBuilder*) mergeFrom:(VerifyFriendReq*) other;
- (VerifyFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (VerifyFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (VerifyFriendReqBuilder*) setUserId:(NSString*) value;
- (VerifyFriendReqBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (VerifyFriendReqBuilder*) setFriendId:(NSString*) value;
- (VerifyFriendReqBuilder*) clearFriendId;

- (BOOL) hasAgree;
- (SInt32) agree;
- (VerifyFriendReqBuilder*) setAgree:(SInt32) value;
- (VerifyFriendReqBuilder*) clearAgree;

- (BOOL) hasContent;
- (NSString*) content;
- (VerifyFriendReqBuilder*) setContent:(NSString*) value;
- (VerifyFriendReqBuilder*) clearContent;
@end

#define VerifyFriendRsp_user_id @"userId"
#define VerifyFriendRsp_friend_id @"friendId"
#define VerifyFriendRsp_result_code @"resultCode"
@interface VerifyFriendRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  BOOL hasResultCode_:1;
  NSString* userId;
  NSString* friendId;
  ResultCode resultCode;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
- (BOOL) hasResultCode;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;
@property (readonly) ResultCode resultCode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (VerifyFriendRspBuilder*) builder;
+ (VerifyFriendRspBuilder*) builder;
+ (VerifyFriendRspBuilder*) builderWithPrototype:(VerifyFriendRsp*) prototype;
- (VerifyFriendRspBuilder*) toBuilder;

+ (VerifyFriendRsp*) parseFromData:(NSData*) data;
+ (VerifyFriendRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VerifyFriendRsp*) parseFromInputStream:(NSInputStream*) input;
+ (VerifyFriendRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VerifyFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (VerifyFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface VerifyFriendRspBuilder : PBGeneratedMessageBuilder {
@private
  VerifyFriendRsp* resultVerifyFriendRsp;
}

- (VerifyFriendRsp*) defaultInstance;

- (VerifyFriendRspBuilder*) clear;
- (VerifyFriendRspBuilder*) clone;

- (VerifyFriendRsp*) build;
- (VerifyFriendRsp*) buildPartial;

- (VerifyFriendRspBuilder*) mergeFrom:(VerifyFriendRsp*) other;
- (VerifyFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (VerifyFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (VerifyFriendRspBuilder*) setUserId:(NSString*) value;
- (VerifyFriendRspBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (VerifyFriendRspBuilder*) setFriendId:(NSString*) value;
- (VerifyFriendRspBuilder*) clearFriendId;

- (BOOL) hasResultCode;
- (ResultCode) resultCode;
- (VerifyFriendRspBuilder*) setResultCode:(ResultCode) value;
- (VerifyFriendRspBuilder*) clearResultCode;
@end

#define DelFriendReq_user_id @"userId"
#define DelFriendReq_friend_id @"friendId"
@interface DelFriendReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  NSString* userId;
  NSString* friendId;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DelFriendReqBuilder*) builder;
+ (DelFriendReqBuilder*) builder;
+ (DelFriendReqBuilder*) builderWithPrototype:(DelFriendReq*) prototype;
- (DelFriendReqBuilder*) toBuilder;

+ (DelFriendReq*) parseFromData:(NSData*) data;
+ (DelFriendReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DelFriendReq*) parseFromInputStream:(NSInputStream*) input;
+ (DelFriendReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DelFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DelFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DelFriendReqBuilder : PBGeneratedMessageBuilder {
@private
  DelFriendReq* resultDelFriendReq;
}

- (DelFriendReq*) defaultInstance;

- (DelFriendReqBuilder*) clear;
- (DelFriendReqBuilder*) clone;

- (DelFriendReq*) build;
- (DelFriendReq*) buildPartial;

- (DelFriendReqBuilder*) mergeFrom:(DelFriendReq*) other;
- (DelFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DelFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (DelFriendReqBuilder*) setUserId:(NSString*) value;
- (DelFriendReqBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (DelFriendReqBuilder*) setFriendId:(NSString*) value;
- (DelFriendReqBuilder*) clearFriendId;
@end

#define DelFriendRsp_user_id @"userId"
#define DelFriendRsp_friend_id @"friendId"
#define DelFriendRsp_result_code @"resultCode"
@interface DelFriendRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  BOOL hasResultCode_:1;
  NSString* userId;
  NSString* friendId;
  ResultCode resultCode;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
- (BOOL) hasResultCode;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;
@property (readonly) ResultCode resultCode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DelFriendRspBuilder*) builder;
+ (DelFriendRspBuilder*) builder;
+ (DelFriendRspBuilder*) builderWithPrototype:(DelFriendRsp*) prototype;
- (DelFriendRspBuilder*) toBuilder;

+ (DelFriendRsp*) parseFromData:(NSData*) data;
+ (DelFriendRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DelFriendRsp*) parseFromInputStream:(NSInputStream*) input;
+ (DelFriendRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DelFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DelFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DelFriendRspBuilder : PBGeneratedMessageBuilder {
@private
  DelFriendRsp* resultDelFriendRsp;
}

- (DelFriendRsp*) defaultInstance;

- (DelFriendRspBuilder*) clear;
- (DelFriendRspBuilder*) clone;

- (DelFriendRsp*) build;
- (DelFriendRsp*) buildPartial;

- (DelFriendRspBuilder*) mergeFrom:(DelFriendRsp*) other;
- (DelFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DelFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (DelFriendRspBuilder*) setUserId:(NSString*) value;
- (DelFriendRspBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (DelFriendRspBuilder*) setFriendId:(NSString*) value;
- (DelFriendRspBuilder*) clearFriendId;

- (BOOL) hasResultCode;
- (ResultCode) resultCode;
- (DelFriendRspBuilder*) setResultCode:(ResultCode) value;
- (DelFriendRspBuilder*) clearResultCode;
@end

#define ModifyFriendReq_user_id @"userId"
#define ModifyFriendReq_friend_id @"friendId"
#define ModifyFriendReq_friend_remark @"friendRemark"
@interface ModifyFriendReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  BOOL hasFriendRemark_:1;
  NSString* userId;
  NSString* friendId;
  NSString* friendRemark;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
- (BOOL) hasFriendRemark;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;
@property (readonly, strong) NSString* friendRemark;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ModifyFriendReqBuilder*) builder;
+ (ModifyFriendReqBuilder*) builder;
+ (ModifyFriendReqBuilder*) builderWithPrototype:(ModifyFriendReq*) prototype;
- (ModifyFriendReqBuilder*) toBuilder;

+ (ModifyFriendReq*) parseFromData:(NSData*) data;
+ (ModifyFriendReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ModifyFriendReq*) parseFromInputStream:(NSInputStream*) input;
+ (ModifyFriendReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ModifyFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ModifyFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ModifyFriendReqBuilder : PBGeneratedMessageBuilder {
@private
  ModifyFriendReq* resultModifyFriendReq;
}

- (ModifyFriendReq*) defaultInstance;

- (ModifyFriendReqBuilder*) clear;
- (ModifyFriendReqBuilder*) clone;

- (ModifyFriendReq*) build;
- (ModifyFriendReq*) buildPartial;

- (ModifyFriendReqBuilder*) mergeFrom:(ModifyFriendReq*) other;
- (ModifyFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ModifyFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (ModifyFriendReqBuilder*) setUserId:(NSString*) value;
- (ModifyFriendReqBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (ModifyFriendReqBuilder*) setFriendId:(NSString*) value;
- (ModifyFriendReqBuilder*) clearFriendId;

- (BOOL) hasFriendRemark;
- (NSString*) friendRemark;
- (ModifyFriendReqBuilder*) setFriendRemark:(NSString*) value;
- (ModifyFriendReqBuilder*) clearFriendRemark;
@end

#define ModifyFriendRsp_user_id @"userId"
#define ModifyFriendRsp_friend_id @"friendId"
#define ModifyFriendRsp_result_code @"resultCode"
@interface ModifyFriendRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  BOOL hasResultCode_:1;
  NSString* userId;
  NSString* friendId;
  ResultCode resultCode;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
- (BOOL) hasResultCode;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;
@property (readonly) ResultCode resultCode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ModifyFriendRspBuilder*) builder;
+ (ModifyFriendRspBuilder*) builder;
+ (ModifyFriendRspBuilder*) builderWithPrototype:(ModifyFriendRsp*) prototype;
- (ModifyFriendRspBuilder*) toBuilder;

+ (ModifyFriendRsp*) parseFromData:(NSData*) data;
+ (ModifyFriendRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ModifyFriendRsp*) parseFromInputStream:(NSInputStream*) input;
+ (ModifyFriendRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ModifyFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ModifyFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ModifyFriendRspBuilder : PBGeneratedMessageBuilder {
@private
  ModifyFriendRsp* resultModifyFriendRsp;
}

- (ModifyFriendRsp*) defaultInstance;

- (ModifyFriendRspBuilder*) clear;
- (ModifyFriendRspBuilder*) clone;

- (ModifyFriendRsp*) build;
- (ModifyFriendRsp*) buildPartial;

- (ModifyFriendRspBuilder*) mergeFrom:(ModifyFriendRsp*) other;
- (ModifyFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ModifyFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (ModifyFriendRspBuilder*) setUserId:(NSString*) value;
- (ModifyFriendRspBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (ModifyFriendRspBuilder*) setFriendId:(NSString*) value;
- (ModifyFriendRspBuilder*) clearFriendId;

- (BOOL) hasResultCode;
- (ResultCode) resultCode;
- (ModifyFriendRspBuilder*) setResultCode:(ResultCode) value;
- (ModifyFriendRspBuilder*) clearResultCode;
@end

#define ShieldFriendReq_user_id @"userId"
#define ShieldFriendReq_friend_id @"friendId"
@interface ShieldFriendReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  NSString* userId;
  NSString* friendId;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ShieldFriendReqBuilder*) builder;
+ (ShieldFriendReqBuilder*) builder;
+ (ShieldFriendReqBuilder*) builderWithPrototype:(ShieldFriendReq*) prototype;
- (ShieldFriendReqBuilder*) toBuilder;

+ (ShieldFriendReq*) parseFromData:(NSData*) data;
+ (ShieldFriendReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShieldFriendReq*) parseFromInputStream:(NSInputStream*) input;
+ (ShieldFriendReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShieldFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ShieldFriendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ShieldFriendReqBuilder : PBGeneratedMessageBuilder {
@private
  ShieldFriendReq* resultShieldFriendReq;
}

- (ShieldFriendReq*) defaultInstance;

- (ShieldFriendReqBuilder*) clear;
- (ShieldFriendReqBuilder*) clone;

- (ShieldFriendReq*) build;
- (ShieldFriendReq*) buildPartial;

- (ShieldFriendReqBuilder*) mergeFrom:(ShieldFriendReq*) other;
- (ShieldFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ShieldFriendReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (ShieldFriendReqBuilder*) setUserId:(NSString*) value;
- (ShieldFriendReqBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (ShieldFriendReqBuilder*) setFriendId:(NSString*) value;
- (ShieldFriendReqBuilder*) clearFriendId;
@end

#define ShieldFriendRsp_user_id @"userId"
#define ShieldFriendRsp_friend_id @"friendId"
#define ShieldFriendRsp_result_code @"resultCode"
@interface ShieldFriendRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasFriendId_:1;
  BOOL hasResultCode_:1;
  NSString* userId;
  NSString* friendId;
  ResultCode resultCode;
}
- (BOOL) hasUserId;
- (BOOL) hasFriendId;
- (BOOL) hasResultCode;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* friendId;
@property (readonly) ResultCode resultCode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ShieldFriendRspBuilder*) builder;
+ (ShieldFriendRspBuilder*) builder;
+ (ShieldFriendRspBuilder*) builderWithPrototype:(ShieldFriendRsp*) prototype;
- (ShieldFriendRspBuilder*) toBuilder;

+ (ShieldFriendRsp*) parseFromData:(NSData*) data;
+ (ShieldFriendRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShieldFriendRsp*) parseFromInputStream:(NSInputStream*) input;
+ (ShieldFriendRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShieldFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ShieldFriendRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ShieldFriendRspBuilder : PBGeneratedMessageBuilder {
@private
  ShieldFriendRsp* resultShieldFriendRsp;
}

- (ShieldFriendRsp*) defaultInstance;

- (ShieldFriendRspBuilder*) clear;
- (ShieldFriendRspBuilder*) clone;

- (ShieldFriendRsp*) build;
- (ShieldFriendRsp*) buildPartial;

- (ShieldFriendRspBuilder*) mergeFrom:(ShieldFriendRsp*) other;
- (ShieldFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ShieldFriendRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (ShieldFriendRspBuilder*) setUserId:(NSString*) value;
- (ShieldFriendRspBuilder*) clearUserId;

- (BOOL) hasFriendId;
- (NSString*) friendId;
- (ShieldFriendRspBuilder*) setFriendId:(NSString*) value;
- (ShieldFriendRspBuilder*) clearFriendId;

- (BOOL) hasResultCode;
- (ResultCode) resultCode;
- (ShieldFriendRspBuilder*) setResultCode:(ResultCode) value;
- (ShieldFriendRspBuilder*) clearResultCode;
@end


// @@protoc_insertion_point(global_scope)
