// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "ImHxcommon.pb.h"
// @@protoc_insertion_point(imports)

@class ApnsPushReq;
@class ApnsPushReqBuilder;
@class ApnsPushRsp;
@class ApnsPushRspBuilder;



@interface ImHxapnsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ApnsPushReq_deviceVersion @"deviceVersion"
#define ApnsPushReq_token @"token"
#define ApnsPushReq_msgid @"msgid"
#define ApnsPushReq_toid @"toid"
@interface ApnsPushReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDeviceVersion_:1;
  BOOL hasToken_:1;
  BOOL hasMsgid_:1;
  BOOL hasToid_:1;
  NSString* deviceVersion;
  NSString* token;
  NSString* msgid;
  NSString* toid;
}
- (BOOL) hasDeviceVersion;
- (BOOL) hasToken;
- (BOOL) hasMsgid;
- (BOOL) hasToid;
@property (readonly, strong) NSString* deviceVersion;
@property (readonly, strong) NSString* token;
@property (readonly, strong) NSString* msgid;
@property (readonly, strong) NSString* toid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ApnsPushReqBuilder*) builder;
+ (ApnsPushReqBuilder*) builder;
+ (ApnsPushReqBuilder*) builderWithPrototype:(ApnsPushReq*) prototype;
- (ApnsPushReqBuilder*) toBuilder;

+ (ApnsPushReq*) parseFromData:(NSData*) data;
+ (ApnsPushReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ApnsPushReq*) parseFromInputStream:(NSInputStream*) input;
+ (ApnsPushReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ApnsPushReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ApnsPushReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ApnsPushReqBuilder : PBGeneratedMessageBuilder {
@private
  ApnsPushReq* resultApnsPushReq;
}

- (ApnsPushReq*) defaultInstance;

- (ApnsPushReqBuilder*) clear;
- (ApnsPushReqBuilder*) clone;

- (ApnsPushReq*) build;
- (ApnsPushReq*) buildPartial;

- (ApnsPushReqBuilder*) mergeFrom:(ApnsPushReq*) other;
- (ApnsPushReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ApnsPushReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceVersion;
- (NSString*) deviceVersion;
- (ApnsPushReqBuilder*) setDeviceVersion:(NSString*) value;
- (ApnsPushReqBuilder*) clearDeviceVersion;

- (BOOL) hasToken;
- (NSString*) token;
- (ApnsPushReqBuilder*) setToken:(NSString*) value;
- (ApnsPushReqBuilder*) clearToken;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (ApnsPushReqBuilder*) setMsgid:(NSString*) value;
- (ApnsPushReqBuilder*) clearMsgid;

- (BOOL) hasToid;
- (NSString*) toid;
- (ApnsPushReqBuilder*) setToid:(NSString*) value;
- (ApnsPushReqBuilder*) clearToid;
@end

#define ApnsPushRsp_code @"code"
@interface ApnsPushRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCode_:1;
  ResultCode code;
}
- (BOOL) hasCode;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ApnsPushRspBuilder*) builder;
+ (ApnsPushRspBuilder*) builder;
+ (ApnsPushRspBuilder*) builderWithPrototype:(ApnsPushRsp*) prototype;
- (ApnsPushRspBuilder*) toBuilder;

+ (ApnsPushRsp*) parseFromData:(NSData*) data;
+ (ApnsPushRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ApnsPushRsp*) parseFromInputStream:(NSInputStream*) input;
+ (ApnsPushRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ApnsPushRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ApnsPushRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ApnsPushRspBuilder : PBGeneratedMessageBuilder {
@private
  ApnsPushRsp* resultApnsPushRsp;
}

- (ApnsPushRsp*) defaultInstance;

- (ApnsPushRspBuilder*) clear;
- (ApnsPushRspBuilder*) clone;

- (ApnsPushRsp*) build;
- (ApnsPushRsp*) buildPartial;

- (ApnsPushRspBuilder*) mergeFrom:(ApnsPushRsp*) other;
- (ApnsPushRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ApnsPushRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (ResultCode) code;
- (ApnsPushRspBuilder*) setCode:(ResultCode) value;
- (ApnsPushRspBuilder*) clearCode;
@end


// @@protoc_insertion_point(global_scope)
