// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "ImHxcommon.pb.h"
// @@protoc_insertion_point(imports)

@class pushAuthReq;
@class pushAuthReqBuilder;
@class pushAuthRsp;
@class pushAuthRspBuilder;
@class pushMsgReq;
@class pushMsgReqBuilder;
@class pushMsgRsp;
@class pushMsgRspBuilder;



@interface ImHxbpnRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define pushMsgReq_msgid @"msgid"
#define pushMsgReq_fromid @"fromid"
#define pushMsgReq_toid @"toid"
#define pushMsgReq_content @"content"
#define pushMsgReq_msgtype @"msgtype"
@interface pushMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsgid_:1;
  BOOL hasFromid_:1;
  BOOL hasToid_:1;
  BOOL hasContent_:1;
  BOOL hasMsgtype_:1;
  NSString* msgid;
  NSString* fromid;
  NSString* toid;
  NSString* content;
  NSString* msgtype;
}
- (BOOL) hasMsgid;
- (BOOL) hasFromid;
- (BOOL) hasToid;
- (BOOL) hasContent;
- (BOOL) hasMsgtype;
@property (readonly, strong) NSString* msgid;
@property (readonly, strong) NSString* fromid;
@property (readonly, strong) NSString* toid;
@property (readonly, strong) NSString* content;
@property (readonly, strong) NSString* msgtype;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (pushMsgReqBuilder*) builder;
+ (pushMsgReqBuilder*) builder;
+ (pushMsgReqBuilder*) builderWithPrototype:(pushMsgReq*) prototype;
- (pushMsgReqBuilder*) toBuilder;

+ (pushMsgReq*) parseFromData:(NSData*) data;
+ (pushMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (pushMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (pushMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (pushMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (pushMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface pushMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  pushMsgReq* resultPushMsgReq;
}

- (pushMsgReq*) defaultInstance;

- (pushMsgReqBuilder*) clear;
- (pushMsgReqBuilder*) clone;

- (pushMsgReq*) build;
- (pushMsgReq*) buildPartial;

- (pushMsgReqBuilder*) mergeFrom:(pushMsgReq*) other;
- (pushMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (pushMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (pushMsgReqBuilder*) setMsgid:(NSString*) value;
- (pushMsgReqBuilder*) clearMsgid;

- (BOOL) hasFromid;
- (NSString*) fromid;
- (pushMsgReqBuilder*) setFromid:(NSString*) value;
- (pushMsgReqBuilder*) clearFromid;

- (BOOL) hasToid;
- (NSString*) toid;
- (pushMsgReqBuilder*) setToid:(NSString*) value;
- (pushMsgReqBuilder*) clearToid;

- (BOOL) hasContent;
- (NSString*) content;
- (pushMsgReqBuilder*) setContent:(NSString*) value;
- (pushMsgReqBuilder*) clearContent;

- (BOOL) hasMsgtype;
- (NSString*) msgtype;
- (pushMsgReqBuilder*) setMsgtype:(NSString*) value;
- (pushMsgReqBuilder*) clearMsgtype;
@end

#define pushMsgRsp_toid @"toid"
#define pushMsgRsp_msgid @"msgid"
#define pushMsgRsp_ack @"ack"
#define pushMsgRsp_read @"read"
@interface pushMsgRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasToid_:1;
  BOOL hasMsgid_:1;
  BOOL hasAck_:1;
  BOOL hasRead_:1;
  NSString* toid;
  NSString* msgid;
  NSString* ack;
  NSString* read;
}
- (BOOL) hasToid;
- (BOOL) hasMsgid;
- (BOOL) hasAck;
- (BOOL) hasRead;
@property (readonly, strong) NSString* toid;
@property (readonly, strong) NSString* msgid;
@property (readonly, strong) NSString* ack;
@property (readonly, strong) NSString* read;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (pushMsgRspBuilder*) builder;
+ (pushMsgRspBuilder*) builder;
+ (pushMsgRspBuilder*) builderWithPrototype:(pushMsgRsp*) prototype;
- (pushMsgRspBuilder*) toBuilder;

+ (pushMsgRsp*) parseFromData:(NSData*) data;
+ (pushMsgRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (pushMsgRsp*) parseFromInputStream:(NSInputStream*) input;
+ (pushMsgRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (pushMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (pushMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface pushMsgRspBuilder : PBGeneratedMessageBuilder {
@private
  pushMsgRsp* resultPushMsgRsp;
}

- (pushMsgRsp*) defaultInstance;

- (pushMsgRspBuilder*) clear;
- (pushMsgRspBuilder*) clone;

- (pushMsgRsp*) build;
- (pushMsgRsp*) buildPartial;

- (pushMsgRspBuilder*) mergeFrom:(pushMsgRsp*) other;
- (pushMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (pushMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToid;
- (NSString*) toid;
- (pushMsgRspBuilder*) setToid:(NSString*) value;
- (pushMsgRspBuilder*) clearToid;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (pushMsgRspBuilder*) setMsgid:(NSString*) value;
- (pushMsgRspBuilder*) clearMsgid;

- (BOOL) hasAck;
- (NSString*) ack;
- (pushMsgRspBuilder*) setAck:(NSString*) value;
- (pushMsgRspBuilder*) clearAck;

- (BOOL) hasRead;
- (NSString*) read;
- (pushMsgRspBuilder*) setRead:(NSString*) value;
- (pushMsgRspBuilder*) clearRead;
@end

#define pushAuthReq_ip @"ip"
#define pushAuthReq_port @"port"
@interface pushAuthReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIp_:1;
  BOOL hasPort_:1;
  NSString* ip;
  NSString* port;
}
- (BOOL) hasIp;
- (BOOL) hasPort;
@property (readonly, strong) NSString* ip;
@property (readonly, strong) NSString* port;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (pushAuthReqBuilder*) builder;
+ (pushAuthReqBuilder*) builder;
+ (pushAuthReqBuilder*) builderWithPrototype:(pushAuthReq*) prototype;
- (pushAuthReqBuilder*) toBuilder;

+ (pushAuthReq*) parseFromData:(NSData*) data;
+ (pushAuthReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (pushAuthReq*) parseFromInputStream:(NSInputStream*) input;
+ (pushAuthReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (pushAuthReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (pushAuthReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface pushAuthReqBuilder : PBGeneratedMessageBuilder {
@private
  pushAuthReq* resultPushAuthReq;
}

- (pushAuthReq*) defaultInstance;

- (pushAuthReqBuilder*) clear;
- (pushAuthReqBuilder*) clone;

- (pushAuthReq*) build;
- (pushAuthReq*) buildPartial;

- (pushAuthReqBuilder*) mergeFrom:(pushAuthReq*) other;
- (pushAuthReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (pushAuthReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIp;
- (NSString*) ip;
- (pushAuthReqBuilder*) setIp:(NSString*) value;
- (pushAuthReqBuilder*) clearIp;

- (BOOL) hasPort;
- (NSString*) port;
- (pushAuthReqBuilder*) setPort:(NSString*) value;
- (pushAuthReqBuilder*) clearPort;
@end

#define pushAuthRsp_code @"code"
@interface pushAuthRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCode_:1;
  ResultCode code;
}
- (BOOL) hasCode;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (pushAuthRspBuilder*) builder;
+ (pushAuthRspBuilder*) builder;
+ (pushAuthRspBuilder*) builderWithPrototype:(pushAuthRsp*) prototype;
- (pushAuthRspBuilder*) toBuilder;

+ (pushAuthRsp*) parseFromData:(NSData*) data;
+ (pushAuthRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (pushAuthRsp*) parseFromInputStream:(NSInputStream*) input;
+ (pushAuthRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (pushAuthRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (pushAuthRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface pushAuthRspBuilder : PBGeneratedMessageBuilder {
@private
  pushAuthRsp* resultPushAuthRsp;
}

- (pushAuthRsp*) defaultInstance;

- (pushAuthRspBuilder*) clear;
- (pushAuthRspBuilder*) clone;

- (pushAuthRsp*) build;
- (pushAuthRsp*) buildPartial;

- (pushAuthRspBuilder*) mergeFrom:(pushAuthRsp*) other;
- (pushAuthRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (pushAuthRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (ResultCode) code;
- (pushAuthRspBuilder*) setCode:(ResultCode) value;
- (pushAuthRspBuilder*) clearCode;
@end


// @@protoc_insertion_point(global_scope)
