// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "ImHxcommon.pb.h"
// @@protoc_insertion_point(imports)

@class BatchMsgAckReq;
@class BatchMsgAckReqBuilder;
@class BatchMsgAckRsp;
@class BatchMsgAckRspBuilder;
@class BatchMsgReadReq;
@class BatchMsgReadReqBuilder;
@class BatchMsgReadRsp;
@class BatchMsgReadRspBuilder;
@class ChatMsg;
@class ChatMsgAckReq;
@class ChatMsgAckReqBuilder;
@class ChatMsgAckRsp;
@class ChatMsgAckRspBuilder;
@class ChatMsgBuilder;
@class ChatMsgReadReq;
@class ChatMsgReadReqBuilder;
@class ChatMsgReadRsp;
@class ChatMsgReadRspBuilder;
@class ChatMsgRsp;
@class ChatMsgRspBuilder;
@class OfflineMsgReq;
@class OfflineMsgReqBuilder;
@class OfflineMsgRsp;
@class OfflineMsgRspBuilder;
@class OfflineMsgSum;
@class OfflineMsgSumBuilder;
@class OfflineMsgSumReq;
@class OfflineMsgSumReqBuilder;
@class OfflineMsgSumRsp;
@class OfflineMsgSumRspBuilder;
@class PfOfflineMsgReq;
@class PfOfflineMsgReqBuilder;
@class PfOfflineMsgRsp;
@class PfOfflineMsgRspBuilder;



@interface ImHxmessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ChatMsg_msgid @"msgid"
#define ChatMsg_guid @"guid"
#define ChatMsg_fromid @"fromid"
#define ChatMsg_toid @"toid"
#define ChatMsg_sessiontype @"sessiontype"
#define ChatMsg_msgtype @"msgtype"
#define ChatMsg_sendtime @"sendtime"
#define ChatMsg_content @"content"
#define ChatMsg_contenttype @"contenttype"
#define ChatMsg_isreaded @"isreaded"
#define ChatMsg_color @"color"
@interface ChatMsg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsreaded_:1;
  BOOL hasSendtime_:1;
  BOOL hasColor_:1;
  BOOL hasMsgid_:1;
  BOOL hasGuid_:1;
  BOOL hasFromid_:1;
  BOOL hasToid_:1;
  BOOL hasSessiontype_:1;
  BOOL hasMsgtype_:1;
  BOOL hasContent_:1;
  BOOL hasContenttype_:1;
  BOOL isreaded_:1;
  UInt64 sendtime;
  SInt32 color;
  NSString* msgid;
  NSString* guid;
  NSString* fromid;
  NSString* toid;
  NSString* sessiontype;
  NSString* msgtype;
  NSString* content;
  NSString* contenttype;
}
- (BOOL) hasMsgid;
- (BOOL) hasGuid;
- (BOOL) hasFromid;
- (BOOL) hasToid;
- (BOOL) hasSessiontype;
- (BOOL) hasMsgtype;
- (BOOL) hasSendtime;
- (BOOL) hasContent;
- (BOOL) hasContenttype;
- (BOOL) hasIsreaded;
- (BOOL) hasColor;
@property (readonly, strong) NSString* msgid;
@property (readonly, strong) NSString* guid;
@property (readonly, strong) NSString* fromid;
@property (readonly, strong) NSString* toid;
@property (readonly, strong) NSString* sessiontype;
@property (readonly, strong) NSString* msgtype;
@property (readonly) UInt64 sendtime;
@property (readonly, strong) NSString* content;
@property (readonly, strong) NSString* contenttype;
- (BOOL) isreaded;
@property (readonly) SInt32 color;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatMsgBuilder*) builder;
+ (ChatMsgBuilder*) builder;
+ (ChatMsgBuilder*) builderWithPrototype:(ChatMsg*) prototype;
- (ChatMsgBuilder*) toBuilder;

+ (ChatMsg*) parseFromData:(NSData*) data;
+ (ChatMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsg*) parseFromInputStream:(NSInputStream*) input;
+ (ChatMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatMsgBuilder : PBGeneratedMessageBuilder {
@private
  ChatMsg* resultChatMsg;
}

- (ChatMsg*) defaultInstance;

- (ChatMsgBuilder*) clear;
- (ChatMsgBuilder*) clone;

- (ChatMsg*) build;
- (ChatMsg*) buildPartial;

- (ChatMsgBuilder*) mergeFrom:(ChatMsg*) other;
- (ChatMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (ChatMsgBuilder*) setMsgid:(NSString*) value;
- (ChatMsgBuilder*) clearMsgid;

- (BOOL) hasGuid;
- (NSString*) guid;
- (ChatMsgBuilder*) setGuid:(NSString*) value;
- (ChatMsgBuilder*) clearGuid;

- (BOOL) hasFromid;
- (NSString*) fromid;
- (ChatMsgBuilder*) setFromid:(NSString*) value;
- (ChatMsgBuilder*) clearFromid;

- (BOOL) hasToid;
- (NSString*) toid;
- (ChatMsgBuilder*) setToid:(NSString*) value;
- (ChatMsgBuilder*) clearToid;

- (BOOL) hasSessiontype;
- (NSString*) sessiontype;
- (ChatMsgBuilder*) setSessiontype:(NSString*) value;
- (ChatMsgBuilder*) clearSessiontype;

- (BOOL) hasMsgtype;
- (NSString*) msgtype;
- (ChatMsgBuilder*) setMsgtype:(NSString*) value;
- (ChatMsgBuilder*) clearMsgtype;

- (BOOL) hasSendtime;
- (UInt64) sendtime;
- (ChatMsgBuilder*) setSendtime:(UInt64) value;
- (ChatMsgBuilder*) clearSendtime;

- (BOOL) hasContent;
- (NSString*) content;
- (ChatMsgBuilder*) setContent:(NSString*) value;
- (ChatMsgBuilder*) clearContent;

- (BOOL) hasContenttype;
- (NSString*) contenttype;
- (ChatMsgBuilder*) setContenttype:(NSString*) value;
- (ChatMsgBuilder*) clearContenttype;

- (BOOL) hasIsreaded;
- (BOOL) isreaded;
- (ChatMsgBuilder*) setIsreaded:(BOOL) value;
- (ChatMsgBuilder*) clearIsreaded;

- (BOOL) hasColor;
- (SInt32) color;
- (ChatMsgBuilder*) setColor:(SInt32) value;
- (ChatMsgBuilder*) clearColor;
@end

#define ChatMsgRsp_userid @"userid"
#define ChatMsgRsp_guid @"guid"
#define ChatMsgRsp_code @"code"
@interface ChatMsgRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasGuid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  NSString* guid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasGuid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* guid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatMsgRspBuilder*) builder;
+ (ChatMsgRspBuilder*) builder;
+ (ChatMsgRspBuilder*) builderWithPrototype:(ChatMsgRsp*) prototype;
- (ChatMsgRspBuilder*) toBuilder;

+ (ChatMsgRsp*) parseFromData:(NSData*) data;
+ (ChatMsgRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgRsp*) parseFromInputStream:(NSInputStream*) input;
+ (ChatMsgRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatMsgRspBuilder : PBGeneratedMessageBuilder {
@private
  ChatMsgRsp* resultChatMsgRsp;
}

- (ChatMsgRsp*) defaultInstance;

- (ChatMsgRspBuilder*) clear;
- (ChatMsgRspBuilder*) clone;

- (ChatMsgRsp*) build;
- (ChatMsgRsp*) buildPartial;

- (ChatMsgRspBuilder*) mergeFrom:(ChatMsgRsp*) other;
- (ChatMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (ChatMsgRspBuilder*) setUserid:(NSString*) value;
- (ChatMsgRspBuilder*) clearUserid;

- (BOOL) hasGuid;
- (NSString*) guid;
- (ChatMsgRspBuilder*) setGuid:(NSString*) value;
- (ChatMsgRspBuilder*) clearGuid;

- (BOOL) hasCode;
- (ResultCode) code;
- (ChatMsgRspBuilder*) setCode:(ResultCode) value;
- (ChatMsgRspBuilder*) clearCode;
@end

#define ChatMsgAckReq_userid @"userid"
#define ChatMsgAckReq_msgid @"msgid"
@interface ChatMsgAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasMsgid_:1;
  NSString* userid;
  NSString* msgid;
}
- (BOOL) hasUserid;
- (BOOL) hasMsgid;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* msgid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatMsgAckReqBuilder*) builder;
+ (ChatMsgAckReqBuilder*) builder;
+ (ChatMsgAckReqBuilder*) builderWithPrototype:(ChatMsgAckReq*) prototype;
- (ChatMsgAckReqBuilder*) toBuilder;

+ (ChatMsgAckReq*) parseFromData:(NSData*) data;
+ (ChatMsgAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (ChatMsgAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatMsgAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatMsgAckReqBuilder : PBGeneratedMessageBuilder {
@private
  ChatMsgAckReq* resultChatMsgAckReq;
}

- (ChatMsgAckReq*) defaultInstance;

- (ChatMsgAckReqBuilder*) clear;
- (ChatMsgAckReqBuilder*) clone;

- (ChatMsgAckReq*) build;
- (ChatMsgAckReq*) buildPartial;

- (ChatMsgAckReqBuilder*) mergeFrom:(ChatMsgAckReq*) other;
- (ChatMsgAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatMsgAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (ChatMsgAckReqBuilder*) setUserid:(NSString*) value;
- (ChatMsgAckReqBuilder*) clearUserid;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (ChatMsgAckReqBuilder*) setMsgid:(NSString*) value;
- (ChatMsgAckReqBuilder*) clearMsgid;
@end

#define ChatMsgAckRsp_userid @"userid"
#define ChatMsgAckRsp_code @"code"
@interface ChatMsgAckRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatMsgAckRspBuilder*) builder;
+ (ChatMsgAckRspBuilder*) builder;
+ (ChatMsgAckRspBuilder*) builderWithPrototype:(ChatMsgAckRsp*) prototype;
- (ChatMsgAckRspBuilder*) toBuilder;

+ (ChatMsgAckRsp*) parseFromData:(NSData*) data;
+ (ChatMsgAckRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgAckRsp*) parseFromInputStream:(NSInputStream*) input;
+ (ChatMsgAckRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgAckRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatMsgAckRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatMsgAckRspBuilder : PBGeneratedMessageBuilder {
@private
  ChatMsgAckRsp* resultChatMsgAckRsp;
}

- (ChatMsgAckRsp*) defaultInstance;

- (ChatMsgAckRspBuilder*) clear;
- (ChatMsgAckRspBuilder*) clone;

- (ChatMsgAckRsp*) build;
- (ChatMsgAckRsp*) buildPartial;

- (ChatMsgAckRspBuilder*) mergeFrom:(ChatMsgAckRsp*) other;
- (ChatMsgAckRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatMsgAckRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (ChatMsgAckRspBuilder*) setUserid:(NSString*) value;
- (ChatMsgAckRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (ChatMsgAckRspBuilder*) setCode:(ResultCode) value;
- (ChatMsgAckRspBuilder*) clearCode;
@end

#define ChatMsgReadReq_userid @"userid"
#define ChatMsgReadReq_msgid @"msgid"
@interface ChatMsgReadReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasMsgid_:1;
  NSString* userid;
  NSString* msgid;
}
- (BOOL) hasUserid;
- (BOOL) hasMsgid;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* msgid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatMsgReadReqBuilder*) builder;
+ (ChatMsgReadReqBuilder*) builder;
+ (ChatMsgReadReqBuilder*) builderWithPrototype:(ChatMsgReadReq*) prototype;
- (ChatMsgReadReqBuilder*) toBuilder;

+ (ChatMsgReadReq*) parseFromData:(NSData*) data;
+ (ChatMsgReadReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgReadReq*) parseFromInputStream:(NSInputStream*) input;
+ (ChatMsgReadReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgReadReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatMsgReadReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatMsgReadReqBuilder : PBGeneratedMessageBuilder {
@private
  ChatMsgReadReq* resultChatMsgReadReq;
}

- (ChatMsgReadReq*) defaultInstance;

- (ChatMsgReadReqBuilder*) clear;
- (ChatMsgReadReqBuilder*) clone;

- (ChatMsgReadReq*) build;
- (ChatMsgReadReq*) buildPartial;

- (ChatMsgReadReqBuilder*) mergeFrom:(ChatMsgReadReq*) other;
- (ChatMsgReadReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatMsgReadReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (ChatMsgReadReqBuilder*) setUserid:(NSString*) value;
- (ChatMsgReadReqBuilder*) clearUserid;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (ChatMsgReadReqBuilder*) setMsgid:(NSString*) value;
- (ChatMsgReadReqBuilder*) clearMsgid;
@end

#define ChatMsgReadRsp_userid @"userid"
#define ChatMsgReadRsp_code @"code"
@interface ChatMsgReadRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatMsgReadRspBuilder*) builder;
+ (ChatMsgReadRspBuilder*) builder;
+ (ChatMsgReadRspBuilder*) builderWithPrototype:(ChatMsgReadRsp*) prototype;
- (ChatMsgReadRspBuilder*) toBuilder;

+ (ChatMsgReadRsp*) parseFromData:(NSData*) data;
+ (ChatMsgReadRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgReadRsp*) parseFromInputStream:(NSInputStream*) input;
+ (ChatMsgReadRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMsgReadRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatMsgReadRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatMsgReadRspBuilder : PBGeneratedMessageBuilder {
@private
  ChatMsgReadRsp* resultChatMsgReadRsp;
}

- (ChatMsgReadRsp*) defaultInstance;

- (ChatMsgReadRspBuilder*) clear;
- (ChatMsgReadRspBuilder*) clone;

- (ChatMsgReadRsp*) build;
- (ChatMsgReadRsp*) buildPartial;

- (ChatMsgReadRspBuilder*) mergeFrom:(ChatMsgReadRsp*) other;
- (ChatMsgReadRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatMsgReadRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (ChatMsgReadRspBuilder*) setUserid:(NSString*) value;
- (ChatMsgReadRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (ChatMsgReadRspBuilder*) setCode:(ResultCode) value;
- (ChatMsgReadRspBuilder*) clearCode;
@end

#define OfflineMsgSum_category @"category"
#define OfflineMsgSum_fromid @"fromid"
#define OfflineMsgSum_toid @"toid"
#define OfflineMsgSum_unreadedcnt @"unreadedcnt"
#define OfflineMsgSum_lastcontent @"lastcontent"
#define OfflineMsgSum_lastupdate @"lastupdate"
@interface OfflineMsgSum : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLastupdate_:1;
  BOOL hasUnreadedcnt_:1;
  BOOL hasCategory_:1;
  BOOL hasFromid_:1;
  BOOL hasToid_:1;
  BOOL hasLastcontent_:1;
  UInt64 lastupdate;
  SInt32 unreadedcnt;
  NSString* category;
  NSString* fromid;
  NSString* toid;
  NSString* lastcontent;
}
- (BOOL) hasCategory;
- (BOOL) hasFromid;
- (BOOL) hasToid;
- (BOOL) hasUnreadedcnt;
- (BOOL) hasLastcontent;
- (BOOL) hasLastupdate;
@property (readonly, strong) NSString* category;
@property (readonly, strong) NSString* fromid;
@property (readonly, strong) NSString* toid;
@property (readonly) SInt32 unreadedcnt;
@property (readonly, strong) NSString* lastcontent;
@property (readonly) UInt64 lastupdate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OfflineMsgSumBuilder*) builder;
+ (OfflineMsgSumBuilder*) builder;
+ (OfflineMsgSumBuilder*) builderWithPrototype:(OfflineMsgSum*) prototype;
- (OfflineMsgSumBuilder*) toBuilder;

+ (OfflineMsgSum*) parseFromData:(NSData*) data;
+ (OfflineMsgSum*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgSum*) parseFromInputStream:(NSInputStream*) input;
+ (OfflineMsgSum*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgSum*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OfflineMsgSum*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OfflineMsgSumBuilder : PBGeneratedMessageBuilder {
@private
  OfflineMsgSum* resultOfflineMsgSum;
}

- (OfflineMsgSum*) defaultInstance;

- (OfflineMsgSumBuilder*) clear;
- (OfflineMsgSumBuilder*) clone;

- (OfflineMsgSum*) build;
- (OfflineMsgSum*) buildPartial;

- (OfflineMsgSumBuilder*) mergeFrom:(OfflineMsgSum*) other;
- (OfflineMsgSumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OfflineMsgSumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCategory;
- (NSString*) category;
- (OfflineMsgSumBuilder*) setCategory:(NSString*) value;
- (OfflineMsgSumBuilder*) clearCategory;

- (BOOL) hasFromid;
- (NSString*) fromid;
- (OfflineMsgSumBuilder*) setFromid:(NSString*) value;
- (OfflineMsgSumBuilder*) clearFromid;

- (BOOL) hasToid;
- (NSString*) toid;
- (OfflineMsgSumBuilder*) setToid:(NSString*) value;
- (OfflineMsgSumBuilder*) clearToid;

- (BOOL) hasUnreadedcnt;
- (SInt32) unreadedcnt;
- (OfflineMsgSumBuilder*) setUnreadedcnt:(SInt32) value;
- (OfflineMsgSumBuilder*) clearUnreadedcnt;

- (BOOL) hasLastcontent;
- (NSString*) lastcontent;
- (OfflineMsgSumBuilder*) setLastcontent:(NSString*) value;
- (OfflineMsgSumBuilder*) clearLastcontent;

- (BOOL) hasLastupdate;
- (UInt64) lastupdate;
- (OfflineMsgSumBuilder*) setLastupdate:(UInt64) value;
- (OfflineMsgSumBuilder*) clearLastupdate;
@end

#define OfflineMsgSumReq_userid @"userid"
@interface OfflineMsgSumReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  NSString* userid;
}
- (BOOL) hasUserid;
@property (readonly, strong) NSString* userid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OfflineMsgSumReqBuilder*) builder;
+ (OfflineMsgSumReqBuilder*) builder;
+ (OfflineMsgSumReqBuilder*) builderWithPrototype:(OfflineMsgSumReq*) prototype;
- (OfflineMsgSumReqBuilder*) toBuilder;

+ (OfflineMsgSumReq*) parseFromData:(NSData*) data;
+ (OfflineMsgSumReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgSumReq*) parseFromInputStream:(NSInputStream*) input;
+ (OfflineMsgSumReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgSumReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OfflineMsgSumReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OfflineMsgSumReqBuilder : PBGeneratedMessageBuilder {
@private
  OfflineMsgSumReq* resultOfflineMsgSumReq;
}

- (OfflineMsgSumReq*) defaultInstance;

- (OfflineMsgSumReqBuilder*) clear;
- (OfflineMsgSumReqBuilder*) clone;

- (OfflineMsgSumReq*) build;
- (OfflineMsgSumReq*) buildPartial;

- (OfflineMsgSumReqBuilder*) mergeFrom:(OfflineMsgSumReq*) other;
- (OfflineMsgSumReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OfflineMsgSumReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (OfflineMsgSumReqBuilder*) setUserid:(NSString*) value;
- (OfflineMsgSumReqBuilder*) clearUserid;
@end

#define OfflineMsgSumRsp_userid @"userid"
#define OfflineMsgSumRsp_code @"code"
#define OfflineMsgSumRsp_summary @"summary"
@interface OfflineMsgSumRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
  NSMutableArray * summaryArray;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;
@property (readonly, strong) NSArray<OfflineMsgSum*> * summary;
- (OfflineMsgSum*)summaryAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OfflineMsgSumRspBuilder*) builder;
+ (OfflineMsgSumRspBuilder*) builder;
+ (OfflineMsgSumRspBuilder*) builderWithPrototype:(OfflineMsgSumRsp*) prototype;
- (OfflineMsgSumRspBuilder*) toBuilder;

+ (OfflineMsgSumRsp*) parseFromData:(NSData*) data;
+ (OfflineMsgSumRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgSumRsp*) parseFromInputStream:(NSInputStream*) input;
+ (OfflineMsgSumRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgSumRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OfflineMsgSumRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OfflineMsgSumRspBuilder : PBGeneratedMessageBuilder {
@private
  OfflineMsgSumRsp* resultOfflineMsgSumRsp;
}

- (OfflineMsgSumRsp*) defaultInstance;

- (OfflineMsgSumRspBuilder*) clear;
- (OfflineMsgSumRspBuilder*) clone;

- (OfflineMsgSumRsp*) build;
- (OfflineMsgSumRsp*) buildPartial;

- (OfflineMsgSumRspBuilder*) mergeFrom:(OfflineMsgSumRsp*) other;
- (OfflineMsgSumRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OfflineMsgSumRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (OfflineMsgSumRspBuilder*) setUserid:(NSString*) value;
- (OfflineMsgSumRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (OfflineMsgSumRspBuilder*) setCode:(ResultCode) value;
- (OfflineMsgSumRspBuilder*) clearCode;

- (NSMutableArray<OfflineMsgSum*> *)summary;
- (OfflineMsgSum*)summaryAtIndex:(NSUInteger)index;
- (OfflineMsgSumRspBuilder *)addSummary:(OfflineMsgSum*)value;
- (OfflineMsgSumRspBuilder *)setSummaryArray:(NSArray<OfflineMsgSum*> *)array;
- (OfflineMsgSumRspBuilder *)clearSummary;
@end

#define OfflineMsgReq_category @"category"
#define OfflineMsgReq_fromid @"fromid"
#define OfflineMsgReq_toid @"toid"
#define OfflineMsgReq_count @"count"
#define OfflineMsgReq_lastupdate @"lastupdate"
@interface OfflineMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLastupdate_:1;
  BOOL hasCount_:1;
  BOOL hasCategory_:1;
  BOOL hasFromid_:1;
  BOOL hasToid_:1;
  UInt64 lastupdate;
  SInt32 count;
  NSString* category;
  NSString* fromid;
  NSString* toid;
}
- (BOOL) hasCategory;
- (BOOL) hasFromid;
- (BOOL) hasToid;
- (BOOL) hasCount;
- (BOOL) hasLastupdate;
@property (readonly, strong) NSString* category;
@property (readonly, strong) NSString* fromid;
@property (readonly, strong) NSString* toid;
@property (readonly) SInt32 count;
@property (readonly) UInt64 lastupdate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OfflineMsgReqBuilder*) builder;
+ (OfflineMsgReqBuilder*) builder;
+ (OfflineMsgReqBuilder*) builderWithPrototype:(OfflineMsgReq*) prototype;
- (OfflineMsgReqBuilder*) toBuilder;

+ (OfflineMsgReq*) parseFromData:(NSData*) data;
+ (OfflineMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (OfflineMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OfflineMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OfflineMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  OfflineMsgReq* resultOfflineMsgReq;
}

- (OfflineMsgReq*) defaultInstance;

- (OfflineMsgReqBuilder*) clear;
- (OfflineMsgReqBuilder*) clone;

- (OfflineMsgReq*) build;
- (OfflineMsgReq*) buildPartial;

- (OfflineMsgReqBuilder*) mergeFrom:(OfflineMsgReq*) other;
- (OfflineMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OfflineMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCategory;
- (NSString*) category;
- (OfflineMsgReqBuilder*) setCategory:(NSString*) value;
- (OfflineMsgReqBuilder*) clearCategory;

- (BOOL) hasFromid;
- (NSString*) fromid;
- (OfflineMsgReqBuilder*) setFromid:(NSString*) value;
- (OfflineMsgReqBuilder*) clearFromid;

- (BOOL) hasToid;
- (NSString*) toid;
- (OfflineMsgReqBuilder*) setToid:(NSString*) value;
- (OfflineMsgReqBuilder*) clearToid;

- (BOOL) hasCount;
- (SInt32) count;
- (OfflineMsgReqBuilder*) setCount:(SInt32) value;
- (OfflineMsgReqBuilder*) clearCount;

- (BOOL) hasLastupdate;
- (UInt64) lastupdate;
- (OfflineMsgReqBuilder*) setLastupdate:(UInt64) value;
- (OfflineMsgReqBuilder*) clearLastupdate;
@end

#define OfflineMsgRsp_userid @"userid"
#define OfflineMsgRsp_code @"code"
#define OfflineMsgRsp_msglist @"msglist"
@interface OfflineMsgRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
  NSMutableArray * msglistArray;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;
@property (readonly, strong) NSArray<ChatMsg*> * msglist;
- (ChatMsg*)msglistAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OfflineMsgRspBuilder*) builder;
+ (OfflineMsgRspBuilder*) builder;
+ (OfflineMsgRspBuilder*) builderWithPrototype:(OfflineMsgRsp*) prototype;
- (OfflineMsgRspBuilder*) toBuilder;

+ (OfflineMsgRsp*) parseFromData:(NSData*) data;
+ (OfflineMsgRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgRsp*) parseFromInputStream:(NSInputStream*) input;
+ (OfflineMsgRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OfflineMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OfflineMsgRspBuilder : PBGeneratedMessageBuilder {
@private
  OfflineMsgRsp* resultOfflineMsgRsp;
}

- (OfflineMsgRsp*) defaultInstance;

- (OfflineMsgRspBuilder*) clear;
- (OfflineMsgRspBuilder*) clone;

- (OfflineMsgRsp*) build;
- (OfflineMsgRsp*) buildPartial;

- (OfflineMsgRspBuilder*) mergeFrom:(OfflineMsgRsp*) other;
- (OfflineMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OfflineMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (OfflineMsgRspBuilder*) setUserid:(NSString*) value;
- (OfflineMsgRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (OfflineMsgRspBuilder*) setCode:(ResultCode) value;
- (OfflineMsgRspBuilder*) clearCode;

- (NSMutableArray<ChatMsg*> *)msglist;
- (ChatMsg*)msglistAtIndex:(NSUInteger)index;
- (OfflineMsgRspBuilder *)addMsglist:(ChatMsg*)value;
- (OfflineMsgRspBuilder *)setMsglistArray:(NSArray<ChatMsg*> *)array;
- (OfflineMsgRspBuilder *)clearMsglist;
@end

#define PfOfflineMsgReq_msgtypelist @"msgtypelist"
#define PfOfflineMsgReq_userid @"userid"
#define PfOfflineMsgReq_count @"count"
#define PfOfflineMsgReq_lastupdate @"lastupdate"
@interface PfOfflineMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLastupdate_:1;
  BOOL hasCount_:1;
  BOOL hasUserid_:1;
  UInt64 lastupdate;
  SInt32 count;
  NSString* userid;
  NSMutableArray * msgtypelistArray;
}
- (BOOL) hasUserid;
- (BOOL) hasCount;
- (BOOL) hasLastupdate;
@property (readonly, strong) NSArray * msgtypelist;
@property (readonly, strong) NSString* userid;
@property (readonly) SInt32 count;
@property (readonly) UInt64 lastupdate;
- (NSString*)msgtypelistAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PfOfflineMsgReqBuilder*) builder;
+ (PfOfflineMsgReqBuilder*) builder;
+ (PfOfflineMsgReqBuilder*) builderWithPrototype:(PfOfflineMsgReq*) prototype;
- (PfOfflineMsgReqBuilder*) toBuilder;

+ (PfOfflineMsgReq*) parseFromData:(NSData*) data;
+ (PfOfflineMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PfOfflineMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (PfOfflineMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PfOfflineMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PfOfflineMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PfOfflineMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  PfOfflineMsgReq* resultPfOfflineMsgReq;
}

- (PfOfflineMsgReq*) defaultInstance;

- (PfOfflineMsgReqBuilder*) clear;
- (PfOfflineMsgReqBuilder*) clone;

- (PfOfflineMsgReq*) build;
- (PfOfflineMsgReq*) buildPartial;

- (PfOfflineMsgReqBuilder*) mergeFrom:(PfOfflineMsgReq*) other;
- (PfOfflineMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PfOfflineMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)msgtypelist;
- (NSString*)msgtypelistAtIndex:(NSUInteger)index;
- (PfOfflineMsgReqBuilder *)addMsgtypelist:(NSString*)value;
- (PfOfflineMsgReqBuilder *)setMsgtypelistArray:(NSArray *)array;
- (PfOfflineMsgReqBuilder *)clearMsgtypelist;

- (BOOL) hasUserid;
- (NSString*) userid;
- (PfOfflineMsgReqBuilder*) setUserid:(NSString*) value;
- (PfOfflineMsgReqBuilder*) clearUserid;

- (BOOL) hasCount;
- (SInt32) count;
- (PfOfflineMsgReqBuilder*) setCount:(SInt32) value;
- (PfOfflineMsgReqBuilder*) clearCount;

- (BOOL) hasLastupdate;
- (UInt64) lastupdate;
- (PfOfflineMsgReqBuilder*) setLastupdate:(UInt64) value;
- (PfOfflineMsgReqBuilder*) clearLastupdate;
@end

#define PfOfflineMsgRsp_userid @"userid"
#define PfOfflineMsgRsp_msglist @"msglist"
#define PfOfflineMsgRsp_code @"code"
@interface PfOfflineMsgRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
  NSMutableArray * msglistArray;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSArray<ChatMsg*> * msglist;
@property (readonly) ResultCode code;
- (ChatMsg*)msglistAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PfOfflineMsgRspBuilder*) builder;
+ (PfOfflineMsgRspBuilder*) builder;
+ (PfOfflineMsgRspBuilder*) builderWithPrototype:(PfOfflineMsgRsp*) prototype;
- (PfOfflineMsgRspBuilder*) toBuilder;

+ (PfOfflineMsgRsp*) parseFromData:(NSData*) data;
+ (PfOfflineMsgRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PfOfflineMsgRsp*) parseFromInputStream:(NSInputStream*) input;
+ (PfOfflineMsgRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PfOfflineMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PfOfflineMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PfOfflineMsgRspBuilder : PBGeneratedMessageBuilder {
@private
  PfOfflineMsgRsp* resultPfOfflineMsgRsp;
}

- (PfOfflineMsgRsp*) defaultInstance;

- (PfOfflineMsgRspBuilder*) clear;
- (PfOfflineMsgRspBuilder*) clone;

- (PfOfflineMsgRsp*) build;
- (PfOfflineMsgRsp*) buildPartial;

- (PfOfflineMsgRspBuilder*) mergeFrom:(PfOfflineMsgRsp*) other;
- (PfOfflineMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PfOfflineMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (PfOfflineMsgRspBuilder*) setUserid:(NSString*) value;
- (PfOfflineMsgRspBuilder*) clearUserid;

- (NSMutableArray<ChatMsg*> *)msglist;
- (ChatMsg*)msglistAtIndex:(NSUInteger)index;
- (PfOfflineMsgRspBuilder *)addMsglist:(ChatMsg*)value;
- (PfOfflineMsgRspBuilder *)setMsglistArray:(NSArray<ChatMsg*> *)array;
- (PfOfflineMsgRspBuilder *)clearMsglist;

- (BOOL) hasCode;
- (ResultCode) code;
- (PfOfflineMsgRspBuilder*) setCode:(ResultCode) value;
- (PfOfflineMsgRspBuilder*) clearCode;
@end

#define BatchMsgAckReq_userid @"userid"
#define BatchMsgAckReq_msgidlist @"msgidlist"
@interface BatchMsgAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  NSString* userid;
  NSMutableArray * msgidlistArray;
}
- (BOOL) hasUserid;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSArray * msgidlist;
- (NSString*)msgidlistAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BatchMsgAckReqBuilder*) builder;
+ (BatchMsgAckReqBuilder*) builder;
+ (BatchMsgAckReqBuilder*) builderWithPrototype:(BatchMsgAckReq*) prototype;
- (BatchMsgAckReqBuilder*) toBuilder;

+ (BatchMsgAckReq*) parseFromData:(NSData*) data;
+ (BatchMsgAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BatchMsgAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (BatchMsgAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BatchMsgAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BatchMsgAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BatchMsgAckReqBuilder : PBGeneratedMessageBuilder {
@private
  BatchMsgAckReq* resultBatchMsgAckReq;
}

- (BatchMsgAckReq*) defaultInstance;

- (BatchMsgAckReqBuilder*) clear;
- (BatchMsgAckReqBuilder*) clone;

- (BatchMsgAckReq*) build;
- (BatchMsgAckReq*) buildPartial;

- (BatchMsgAckReqBuilder*) mergeFrom:(BatchMsgAckReq*) other;
- (BatchMsgAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BatchMsgAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (BatchMsgAckReqBuilder*) setUserid:(NSString*) value;
- (BatchMsgAckReqBuilder*) clearUserid;

- (NSMutableArray *)msgidlist;
- (NSString*)msgidlistAtIndex:(NSUInteger)index;
- (BatchMsgAckReqBuilder *)addMsgidlist:(NSString*)value;
- (BatchMsgAckReqBuilder *)setMsgidlistArray:(NSArray *)array;
- (BatchMsgAckReqBuilder *)clearMsgidlist;
@end

#define BatchMsgAckRsp_userid @"userid"
#define BatchMsgAckRsp_code @"code"
@interface BatchMsgAckRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BatchMsgAckRspBuilder*) builder;
+ (BatchMsgAckRspBuilder*) builder;
+ (BatchMsgAckRspBuilder*) builderWithPrototype:(BatchMsgAckRsp*) prototype;
- (BatchMsgAckRspBuilder*) toBuilder;

+ (BatchMsgAckRsp*) parseFromData:(NSData*) data;
+ (BatchMsgAckRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BatchMsgAckRsp*) parseFromInputStream:(NSInputStream*) input;
+ (BatchMsgAckRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BatchMsgAckRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BatchMsgAckRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BatchMsgAckRspBuilder : PBGeneratedMessageBuilder {
@private
  BatchMsgAckRsp* resultBatchMsgAckRsp;
}

- (BatchMsgAckRsp*) defaultInstance;

- (BatchMsgAckRspBuilder*) clear;
- (BatchMsgAckRspBuilder*) clone;

- (BatchMsgAckRsp*) build;
- (BatchMsgAckRsp*) buildPartial;

- (BatchMsgAckRspBuilder*) mergeFrom:(BatchMsgAckRsp*) other;
- (BatchMsgAckRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BatchMsgAckRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (BatchMsgAckRspBuilder*) setUserid:(NSString*) value;
- (BatchMsgAckRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (BatchMsgAckRspBuilder*) setCode:(ResultCode) value;
- (BatchMsgAckRspBuilder*) clearCode;
@end

#define BatchMsgReadReq_userid @"userid"
#define BatchMsgReadReq_msgidlist @"msgidlist"
@interface BatchMsgReadReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  NSString* userid;
  NSMutableArray * msgidlistArray;
}
- (BOOL) hasUserid;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSArray * msgidlist;
- (NSString*)msgidlistAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BatchMsgReadReqBuilder*) builder;
+ (BatchMsgReadReqBuilder*) builder;
+ (BatchMsgReadReqBuilder*) builderWithPrototype:(BatchMsgReadReq*) prototype;
- (BatchMsgReadReqBuilder*) toBuilder;

+ (BatchMsgReadReq*) parseFromData:(NSData*) data;
+ (BatchMsgReadReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BatchMsgReadReq*) parseFromInputStream:(NSInputStream*) input;
+ (BatchMsgReadReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BatchMsgReadReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BatchMsgReadReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BatchMsgReadReqBuilder : PBGeneratedMessageBuilder {
@private
  BatchMsgReadReq* resultBatchMsgReadReq;
}

- (BatchMsgReadReq*) defaultInstance;

- (BatchMsgReadReqBuilder*) clear;
- (BatchMsgReadReqBuilder*) clone;

- (BatchMsgReadReq*) build;
- (BatchMsgReadReq*) buildPartial;

- (BatchMsgReadReqBuilder*) mergeFrom:(BatchMsgReadReq*) other;
- (BatchMsgReadReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BatchMsgReadReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (BatchMsgReadReqBuilder*) setUserid:(NSString*) value;
- (BatchMsgReadReqBuilder*) clearUserid;

- (NSMutableArray *)msgidlist;
- (NSString*)msgidlistAtIndex:(NSUInteger)index;
- (BatchMsgReadReqBuilder *)addMsgidlist:(NSString*)value;
- (BatchMsgReadReqBuilder *)setMsgidlistArray:(NSArray *)array;
- (BatchMsgReadReqBuilder *)clearMsgidlist;
@end

#define BatchMsgReadRsp_userid @"userid"
#define BatchMsgReadRsp_code @"code"
@interface BatchMsgReadRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BatchMsgReadRspBuilder*) builder;
+ (BatchMsgReadRspBuilder*) builder;
+ (BatchMsgReadRspBuilder*) builderWithPrototype:(BatchMsgReadRsp*) prototype;
- (BatchMsgReadRspBuilder*) toBuilder;

+ (BatchMsgReadRsp*) parseFromData:(NSData*) data;
+ (BatchMsgReadRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BatchMsgReadRsp*) parseFromInputStream:(NSInputStream*) input;
+ (BatchMsgReadRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BatchMsgReadRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BatchMsgReadRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BatchMsgReadRspBuilder : PBGeneratedMessageBuilder {
@private
  BatchMsgReadRsp* resultBatchMsgReadRsp;
}

- (BatchMsgReadRsp*) defaultInstance;

- (BatchMsgReadRspBuilder*) clear;
- (BatchMsgReadRspBuilder*) clone;

- (BatchMsgReadRsp*) build;
- (BatchMsgReadRsp*) buildPartial;

- (BatchMsgReadRspBuilder*) mergeFrom:(BatchMsgReadRsp*) other;
- (BatchMsgReadRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BatchMsgReadRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (BatchMsgReadRspBuilder*) setUserid:(NSString*) value;
- (BatchMsgReadRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (BatchMsgReadRspBuilder*) setCode:(ResultCode) value;
- (BatchMsgReadRspBuilder*) clearCode;
@end


// @@protoc_insertion_point(global_scope)
