// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "ImHxcommon.pb.h"
// @@protoc_insertion_point(imports)

@class AssignP2CLeaveMsgReq;
@class AssignP2CLeaveMsgReqBuilder;
@class AssignP2CLeaveMsgRsp;
@class AssignP2CLeaveMsgRspBuilder;
@class CloseP2CSessionReq;
@class CloseP2CSessionReqBuilder;
@class CloseP2CSessionRsp;
@class CloseP2CSessionRspBuilder;
@class CreateP2CSessionReq;
@class CreateP2CSessionReqBuilder;
@class CreateP2CSessionRsp;
@class CreateP2CSessionRspBuilder;
@class NotifySwitchP2C;
@class NotifySwitchP2CBuilder;
@class NotifySwitchP2CRsp;
@class NotifySwitchP2CRspBuilder;
@class P2CLeaveMsgReq;
@class P2CLeaveMsgReqBuilder;
@class P2CLeaveMsgRsp;
@class P2CLeaveMsgRspBuilder;
@class P2CMsg;
@class P2CMsgAckReq;
@class P2CMsgAckReqBuilder;
@class P2CMsgAckRsp;
@class P2CMsgAckRspBuilder;
@class P2CMsgBuilder;
@class P2CMsgReadReq;
@class P2CMsgReadReqBuilder;
@class P2CMsgReadRsp;
@class P2CMsgReadRspBuilder;
@class P2CMsgRsp;
@class P2CMsgRspBuilder;
@class P2COfflineMsgReq;
@class P2COfflineMsgReqBuilder;
@class P2COfflineMsgRsp;
@class P2COfflineMsgRspBuilder;
@class P2CSession;
@class P2CSessionBuilder;
@class P2CSwitchEntity;
@class P2CSwitchEntityBuilder;
@class SwitchP2CReq;
@class SwitchP2CReqBuilder;
@class SwitchP2CRsp;
@class SwitchP2CRspBuilder;



@interface ImHxkefuRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define P2CMsg_sessionid @"sessionid"
#define P2CMsg_msgid @"msgid"
#define P2CMsg_guid @"guid"
#define P2CMsg_fromid @"fromid"
#define P2CMsg_toid @"toid"
#define P2CMsg_sendtime @"sendtime"
#define P2CMsg_content @"content"
#define P2CMsg_isread @"isread"
@interface P2CMsg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsread_:1;
  BOOL hasSendtime_:1;
  BOOL hasSessionid_:1;
  BOOL hasMsgid_:1;
  BOOL hasGuid_:1;
  BOOL hasFromid_:1;
  BOOL hasToid_:1;
  BOOL hasContent_:1;
  BOOL isread_:1;
  UInt64 sendtime;
  NSString* sessionid;
  NSString* msgid;
  NSString* guid;
  NSString* fromid;
  NSString* toid;
  NSString* content;
}
- (BOOL) hasSessionid;
- (BOOL) hasMsgid;
- (BOOL) hasGuid;
- (BOOL) hasFromid;
- (BOOL) hasToid;
- (BOOL) hasSendtime;
- (BOOL) hasContent;
- (BOOL) hasIsread;
@property (readonly, strong) NSString* sessionid;
@property (readonly, strong) NSString* msgid;
@property (readonly, strong) NSString* guid;
@property (readonly, strong) NSString* fromid;
@property (readonly, strong) NSString* toid;
@property (readonly) UInt64 sendtime;
@property (readonly, strong) NSString* content;
- (BOOL) isread;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CMsgBuilder*) builder;
+ (P2CMsgBuilder*) builder;
+ (P2CMsgBuilder*) builderWithPrototype:(P2CMsg*) prototype;
- (P2CMsgBuilder*) toBuilder;

+ (P2CMsg*) parseFromData:(NSData*) data;
+ (P2CMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsg*) parseFromInputStream:(NSInputStream*) input;
+ (P2CMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CMsgBuilder : PBGeneratedMessageBuilder {
@private
  P2CMsg* resultP2Cmsg;
}

- (P2CMsg*) defaultInstance;

- (P2CMsgBuilder*) clear;
- (P2CMsgBuilder*) clone;

- (P2CMsg*) build;
- (P2CMsg*) buildPartial;

- (P2CMsgBuilder*) mergeFrom:(P2CMsg*) other;
- (P2CMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessionid;
- (NSString*) sessionid;
- (P2CMsgBuilder*) setSessionid:(NSString*) value;
- (P2CMsgBuilder*) clearSessionid;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (P2CMsgBuilder*) setMsgid:(NSString*) value;
- (P2CMsgBuilder*) clearMsgid;

- (BOOL) hasGuid;
- (NSString*) guid;
- (P2CMsgBuilder*) setGuid:(NSString*) value;
- (P2CMsgBuilder*) clearGuid;

- (BOOL) hasFromid;
- (NSString*) fromid;
- (P2CMsgBuilder*) setFromid:(NSString*) value;
- (P2CMsgBuilder*) clearFromid;

- (BOOL) hasToid;
- (NSString*) toid;
- (P2CMsgBuilder*) setToid:(NSString*) value;
- (P2CMsgBuilder*) clearToid;

- (BOOL) hasSendtime;
- (UInt64) sendtime;
- (P2CMsgBuilder*) setSendtime:(UInt64) value;
- (P2CMsgBuilder*) clearSendtime;

- (BOOL) hasContent;
- (NSString*) content;
- (P2CMsgBuilder*) setContent:(NSString*) value;
- (P2CMsgBuilder*) clearContent;

- (BOOL) hasIsread;
- (BOOL) isread;
- (P2CMsgBuilder*) setIsread:(BOOL) value;
- (P2CMsgBuilder*) clearIsread;
@end

#define P2CSession_consumerid @"consumerid"
#define P2CSession_kefuid @"kefuid"
#define P2CSession_sessionid @"sessionid"
@interface P2CSession : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasConsumerid_:1;
  BOOL hasKefuid_:1;
  BOOL hasSessionid_:1;
  NSString* consumerid;
  NSString* kefuid;
  NSString* sessionid;
}
- (BOOL) hasConsumerid;
- (BOOL) hasKefuid;
- (BOOL) hasSessionid;
@property (readonly, strong) NSString* consumerid;
@property (readonly, strong) NSString* kefuid;
@property (readonly, strong) NSString* sessionid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CSessionBuilder*) builder;
+ (P2CSessionBuilder*) builder;
+ (P2CSessionBuilder*) builderWithPrototype:(P2CSession*) prototype;
- (P2CSessionBuilder*) toBuilder;

+ (P2CSession*) parseFromData:(NSData*) data;
+ (P2CSession*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CSession*) parseFromInputStream:(NSInputStream*) input;
+ (P2CSession*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CSession*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CSession*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CSessionBuilder : PBGeneratedMessageBuilder {
@private
  P2CSession* resultP2Csession;
}

- (P2CSession*) defaultInstance;

- (P2CSessionBuilder*) clear;
- (P2CSessionBuilder*) clone;

- (P2CSession*) build;
- (P2CSession*) buildPartial;

- (P2CSessionBuilder*) mergeFrom:(P2CSession*) other;
- (P2CSessionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CSessionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasConsumerid;
- (NSString*) consumerid;
- (P2CSessionBuilder*) setConsumerid:(NSString*) value;
- (P2CSessionBuilder*) clearConsumerid;

- (BOOL) hasKefuid;
- (NSString*) kefuid;
- (P2CSessionBuilder*) setKefuid:(NSString*) value;
- (P2CSessionBuilder*) clearKefuid;

- (BOOL) hasSessionid;
- (NSString*) sessionid;
- (P2CSessionBuilder*) setSessionid:(NSString*) value;
- (P2CSessionBuilder*) clearSessionid;
@end

#define CreateP2CSessionReq_consumerid @"consumerid"
#define CreateP2CSessionReq_entid @"entid"
#define CreateP2CSessionReq_content @"content"
@interface CreateP2CSessionReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasConsumerid_:1;
  BOOL hasEntid_:1;
  BOOL hasContent_:1;
  NSString* consumerid;
  NSString* entid;
  NSString* content;
}
- (BOOL) hasConsumerid;
- (BOOL) hasEntid;
- (BOOL) hasContent;
@property (readonly, strong) NSString* consumerid;
@property (readonly, strong) NSString* entid;
@property (readonly, strong) NSString* content;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateP2CSessionReqBuilder*) builder;
+ (CreateP2CSessionReqBuilder*) builder;
+ (CreateP2CSessionReqBuilder*) builderWithPrototype:(CreateP2CSessionReq*) prototype;
- (CreateP2CSessionReqBuilder*) toBuilder;

+ (CreateP2CSessionReq*) parseFromData:(NSData*) data;
+ (CreateP2CSessionReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateP2CSessionReq*) parseFromInputStream:(NSInputStream*) input;
+ (CreateP2CSessionReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateP2CSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateP2CSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateP2CSessionReqBuilder : PBGeneratedMessageBuilder {
@private
  CreateP2CSessionReq* resultCreateP2CsessionReq;
}

- (CreateP2CSessionReq*) defaultInstance;

- (CreateP2CSessionReqBuilder*) clear;
- (CreateP2CSessionReqBuilder*) clone;

- (CreateP2CSessionReq*) build;
- (CreateP2CSessionReq*) buildPartial;

- (CreateP2CSessionReqBuilder*) mergeFrom:(CreateP2CSessionReq*) other;
- (CreateP2CSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateP2CSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasConsumerid;
- (NSString*) consumerid;
- (CreateP2CSessionReqBuilder*) setConsumerid:(NSString*) value;
- (CreateP2CSessionReqBuilder*) clearConsumerid;

- (BOOL) hasEntid;
- (NSString*) entid;
- (CreateP2CSessionReqBuilder*) setEntid:(NSString*) value;
- (CreateP2CSessionReqBuilder*) clearEntid;

- (BOOL) hasContent;
- (NSString*) content;
- (CreateP2CSessionReqBuilder*) setContent:(NSString*) value;
- (CreateP2CSessionReqBuilder*) clearContent;
@end

#define CreateP2CSessionRsp_session @"session"
#define CreateP2CSessionRsp_welcomeword @"welcomeword"
#define CreateP2CSessionRsp_resptime @"resptime"
#define CreateP2CSessionRsp_content @"content"
#define CreateP2CSessionRsp_code @"code"
@interface CreateP2CSessionRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasResptime_:1;
  BOOL hasWelcomeword_:1;
  BOOL hasContent_:1;
  BOOL hasSession_:1;
  BOOL hasCode_:1;
  UInt64 resptime;
  NSString* welcomeword;
  NSString* content;
  P2CSession* session;
  ResultCode code;
}
- (BOOL) hasSession;
- (BOOL) hasWelcomeword;
- (BOOL) hasResptime;
- (BOOL) hasContent;
- (BOOL) hasCode;
@property (readonly, strong) P2CSession* session;
@property (readonly, strong) NSString* welcomeword;
@property (readonly) UInt64 resptime;
@property (readonly, strong) NSString* content;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateP2CSessionRspBuilder*) builder;
+ (CreateP2CSessionRspBuilder*) builder;
+ (CreateP2CSessionRspBuilder*) builderWithPrototype:(CreateP2CSessionRsp*) prototype;
- (CreateP2CSessionRspBuilder*) toBuilder;

+ (CreateP2CSessionRsp*) parseFromData:(NSData*) data;
+ (CreateP2CSessionRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateP2CSessionRsp*) parseFromInputStream:(NSInputStream*) input;
+ (CreateP2CSessionRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateP2CSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateP2CSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateP2CSessionRspBuilder : PBGeneratedMessageBuilder {
@private
  CreateP2CSessionRsp* resultCreateP2CsessionRsp;
}

- (CreateP2CSessionRsp*) defaultInstance;

- (CreateP2CSessionRspBuilder*) clear;
- (CreateP2CSessionRspBuilder*) clone;

- (CreateP2CSessionRsp*) build;
- (CreateP2CSessionRsp*) buildPartial;

- (CreateP2CSessionRspBuilder*) mergeFrom:(CreateP2CSessionRsp*) other;
- (CreateP2CSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateP2CSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSession;
- (P2CSession*) session;
- (CreateP2CSessionRspBuilder*) setSession:(P2CSession*) value;
- (CreateP2CSessionRspBuilder*) setSessionBuilder:(P2CSessionBuilder*) builderForValue;
- (CreateP2CSessionRspBuilder*) mergeSession:(P2CSession*) value;
- (CreateP2CSessionRspBuilder*) clearSession;

- (BOOL) hasWelcomeword;
- (NSString*) welcomeword;
- (CreateP2CSessionRspBuilder*) setWelcomeword:(NSString*) value;
- (CreateP2CSessionRspBuilder*) clearWelcomeword;

- (BOOL) hasResptime;
- (UInt64) resptime;
- (CreateP2CSessionRspBuilder*) setResptime:(UInt64) value;
- (CreateP2CSessionRspBuilder*) clearResptime;

- (BOOL) hasContent;
- (NSString*) content;
- (CreateP2CSessionRspBuilder*) setContent:(NSString*) value;
- (CreateP2CSessionRspBuilder*) clearContent;

- (BOOL) hasCode;
- (ResultCode) code;
- (CreateP2CSessionRspBuilder*) setCode:(ResultCode) value;
- (CreateP2CSessionRspBuilder*) clearCode;
@end

#define CloseP2CSessionReq_userid @"userid"
#define CloseP2CSessionReq_entid @"entid"
#define CloseP2CSessionReq_session @"session"
#define CloseP2CSessionReq_content @"content"
@interface CloseP2CSessionReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasEntid_:1;
  BOOL hasContent_:1;
  BOOL hasSession_:1;
  NSString* userid;
  NSString* entid;
  NSString* content;
  P2CSession* session;
}
- (BOOL) hasUserid;
- (BOOL) hasEntid;
- (BOOL) hasSession;
- (BOOL) hasContent;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* entid;
@property (readonly, strong) P2CSession* session;
@property (readonly, strong) NSString* content;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CloseP2CSessionReqBuilder*) builder;
+ (CloseP2CSessionReqBuilder*) builder;
+ (CloseP2CSessionReqBuilder*) builderWithPrototype:(CloseP2CSessionReq*) prototype;
- (CloseP2CSessionReqBuilder*) toBuilder;

+ (CloseP2CSessionReq*) parseFromData:(NSData*) data;
+ (CloseP2CSessionReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CloseP2CSessionReq*) parseFromInputStream:(NSInputStream*) input;
+ (CloseP2CSessionReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CloseP2CSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CloseP2CSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CloseP2CSessionReqBuilder : PBGeneratedMessageBuilder {
@private
  CloseP2CSessionReq* resultCloseP2CsessionReq;
}

- (CloseP2CSessionReq*) defaultInstance;

- (CloseP2CSessionReqBuilder*) clear;
- (CloseP2CSessionReqBuilder*) clone;

- (CloseP2CSessionReq*) build;
- (CloseP2CSessionReq*) buildPartial;

- (CloseP2CSessionReqBuilder*) mergeFrom:(CloseP2CSessionReq*) other;
- (CloseP2CSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CloseP2CSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (CloseP2CSessionReqBuilder*) setUserid:(NSString*) value;
- (CloseP2CSessionReqBuilder*) clearUserid;

- (BOOL) hasEntid;
- (NSString*) entid;
- (CloseP2CSessionReqBuilder*) setEntid:(NSString*) value;
- (CloseP2CSessionReqBuilder*) clearEntid;

- (BOOL) hasSession;
- (P2CSession*) session;
- (CloseP2CSessionReqBuilder*) setSession:(P2CSession*) value;
- (CloseP2CSessionReqBuilder*) setSessionBuilder:(P2CSessionBuilder*) builderForValue;
- (CloseP2CSessionReqBuilder*) mergeSession:(P2CSession*) value;
- (CloseP2CSessionReqBuilder*) clearSession;

- (BOOL) hasContent;
- (NSString*) content;
- (CloseP2CSessionReqBuilder*) setContent:(NSString*) value;
- (CloseP2CSessionReqBuilder*) clearContent;
@end

#define CloseP2CSessionRsp_userid @"userid"
#define CloseP2CSessionRsp_greeting @"greeting"
#define CloseP2CSessionRsp_resptime @"resptime"
#define CloseP2CSessionRsp_content @"content"
#define CloseP2CSessionRsp_code @"code"
@interface CloseP2CSessionRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasResptime_:1;
  BOOL hasUserid_:1;
  BOOL hasGreeting_:1;
  BOOL hasContent_:1;
  BOOL hasCode_:1;
  UInt64 resptime;
  NSString* userid;
  NSString* greeting;
  NSString* content;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasGreeting;
- (BOOL) hasResptime;
- (BOOL) hasContent;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* greeting;
@property (readonly) UInt64 resptime;
@property (readonly, strong) NSString* content;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CloseP2CSessionRspBuilder*) builder;
+ (CloseP2CSessionRspBuilder*) builder;
+ (CloseP2CSessionRspBuilder*) builderWithPrototype:(CloseP2CSessionRsp*) prototype;
- (CloseP2CSessionRspBuilder*) toBuilder;

+ (CloseP2CSessionRsp*) parseFromData:(NSData*) data;
+ (CloseP2CSessionRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CloseP2CSessionRsp*) parseFromInputStream:(NSInputStream*) input;
+ (CloseP2CSessionRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CloseP2CSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CloseP2CSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CloseP2CSessionRspBuilder : PBGeneratedMessageBuilder {
@private
  CloseP2CSessionRsp* resultCloseP2CsessionRsp;
}

- (CloseP2CSessionRsp*) defaultInstance;

- (CloseP2CSessionRspBuilder*) clear;
- (CloseP2CSessionRspBuilder*) clone;

- (CloseP2CSessionRsp*) build;
- (CloseP2CSessionRsp*) buildPartial;

- (CloseP2CSessionRspBuilder*) mergeFrom:(CloseP2CSessionRsp*) other;
- (CloseP2CSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CloseP2CSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (CloseP2CSessionRspBuilder*) setUserid:(NSString*) value;
- (CloseP2CSessionRspBuilder*) clearUserid;

- (BOOL) hasGreeting;
- (NSString*) greeting;
- (CloseP2CSessionRspBuilder*) setGreeting:(NSString*) value;
- (CloseP2CSessionRspBuilder*) clearGreeting;

- (BOOL) hasResptime;
- (UInt64) resptime;
- (CloseP2CSessionRspBuilder*) setResptime:(UInt64) value;
- (CloseP2CSessionRspBuilder*) clearResptime;

- (BOOL) hasContent;
- (NSString*) content;
- (CloseP2CSessionRspBuilder*) setContent:(NSString*) value;
- (CloseP2CSessionRspBuilder*) clearContent;

- (BOOL) hasCode;
- (ResultCode) code;
- (CloseP2CSessionRspBuilder*) setCode:(ResultCode) value;
- (CloseP2CSessionRspBuilder*) clearCode;
@end

#define P2CMsgRsp_userid @"userid"
#define P2CMsgRsp_guid @"guid"
#define P2CMsgRsp_code @"code"
@interface P2CMsgRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasGuid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  NSString* guid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasGuid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* guid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CMsgRspBuilder*) builder;
+ (P2CMsgRspBuilder*) builder;
+ (P2CMsgRspBuilder*) builderWithPrototype:(P2CMsgRsp*) prototype;
- (P2CMsgRspBuilder*) toBuilder;

+ (P2CMsgRsp*) parseFromData:(NSData*) data;
+ (P2CMsgRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgRsp*) parseFromInputStream:(NSInputStream*) input;
+ (P2CMsgRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CMsgRspBuilder : PBGeneratedMessageBuilder {
@private
  P2CMsgRsp* resultP2CmsgRsp;
}

- (P2CMsgRsp*) defaultInstance;

- (P2CMsgRspBuilder*) clear;
- (P2CMsgRspBuilder*) clone;

- (P2CMsgRsp*) build;
- (P2CMsgRsp*) buildPartial;

- (P2CMsgRspBuilder*) mergeFrom:(P2CMsgRsp*) other;
- (P2CMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (P2CMsgRspBuilder*) setUserid:(NSString*) value;
- (P2CMsgRspBuilder*) clearUserid;

- (BOOL) hasGuid;
- (NSString*) guid;
- (P2CMsgRspBuilder*) setGuid:(NSString*) value;
- (P2CMsgRspBuilder*) clearGuid;

- (BOOL) hasCode;
- (ResultCode) code;
- (P2CMsgRspBuilder*) setCode:(ResultCode) value;
- (P2CMsgRspBuilder*) clearCode;
@end

#define P2CMsgAckReq_userid @"userid"
#define P2CMsgAckReq_msgid @"msgid"
@interface P2CMsgAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasMsgid_:1;
  NSString* userid;
  NSString* msgid;
}
- (BOOL) hasUserid;
- (BOOL) hasMsgid;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* msgid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CMsgAckReqBuilder*) builder;
+ (P2CMsgAckReqBuilder*) builder;
+ (P2CMsgAckReqBuilder*) builderWithPrototype:(P2CMsgAckReq*) prototype;
- (P2CMsgAckReqBuilder*) toBuilder;

+ (P2CMsgAckReq*) parseFromData:(NSData*) data;
+ (P2CMsgAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (P2CMsgAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CMsgAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CMsgAckReqBuilder : PBGeneratedMessageBuilder {
@private
  P2CMsgAckReq* resultP2CmsgAckReq;
}

- (P2CMsgAckReq*) defaultInstance;

- (P2CMsgAckReqBuilder*) clear;
- (P2CMsgAckReqBuilder*) clone;

- (P2CMsgAckReq*) build;
- (P2CMsgAckReq*) buildPartial;

- (P2CMsgAckReqBuilder*) mergeFrom:(P2CMsgAckReq*) other;
- (P2CMsgAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CMsgAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (P2CMsgAckReqBuilder*) setUserid:(NSString*) value;
- (P2CMsgAckReqBuilder*) clearUserid;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (P2CMsgAckReqBuilder*) setMsgid:(NSString*) value;
- (P2CMsgAckReqBuilder*) clearMsgid;
@end

#define P2CMsgAckRsp_userid @"userid"
#define P2CMsgAckRsp_code @"code"
@interface P2CMsgAckRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CMsgAckRspBuilder*) builder;
+ (P2CMsgAckRspBuilder*) builder;
+ (P2CMsgAckRspBuilder*) builderWithPrototype:(P2CMsgAckRsp*) prototype;
- (P2CMsgAckRspBuilder*) toBuilder;

+ (P2CMsgAckRsp*) parseFromData:(NSData*) data;
+ (P2CMsgAckRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgAckRsp*) parseFromInputStream:(NSInputStream*) input;
+ (P2CMsgAckRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgAckRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CMsgAckRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CMsgAckRspBuilder : PBGeneratedMessageBuilder {
@private
  P2CMsgAckRsp* resultP2CmsgAckRsp;
}

- (P2CMsgAckRsp*) defaultInstance;

- (P2CMsgAckRspBuilder*) clear;
- (P2CMsgAckRspBuilder*) clone;

- (P2CMsgAckRsp*) build;
- (P2CMsgAckRsp*) buildPartial;

- (P2CMsgAckRspBuilder*) mergeFrom:(P2CMsgAckRsp*) other;
- (P2CMsgAckRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CMsgAckRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (P2CMsgAckRspBuilder*) setUserid:(NSString*) value;
- (P2CMsgAckRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (P2CMsgAckRspBuilder*) setCode:(ResultCode) value;
- (P2CMsgAckRspBuilder*) clearCode;
@end

#define P2CMsgReadReq_userid @"userid"
#define P2CMsgReadReq_msgid @"msgid"
@interface P2CMsgReadReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasMsgid_:1;
  NSString* userid;
  NSString* msgid;
}
- (BOOL) hasUserid;
- (BOOL) hasMsgid;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* msgid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CMsgReadReqBuilder*) builder;
+ (P2CMsgReadReqBuilder*) builder;
+ (P2CMsgReadReqBuilder*) builderWithPrototype:(P2CMsgReadReq*) prototype;
- (P2CMsgReadReqBuilder*) toBuilder;

+ (P2CMsgReadReq*) parseFromData:(NSData*) data;
+ (P2CMsgReadReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgReadReq*) parseFromInputStream:(NSInputStream*) input;
+ (P2CMsgReadReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgReadReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CMsgReadReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CMsgReadReqBuilder : PBGeneratedMessageBuilder {
@private
  P2CMsgReadReq* resultP2CmsgReadReq;
}

- (P2CMsgReadReq*) defaultInstance;

- (P2CMsgReadReqBuilder*) clear;
- (P2CMsgReadReqBuilder*) clone;

- (P2CMsgReadReq*) build;
- (P2CMsgReadReq*) buildPartial;

- (P2CMsgReadReqBuilder*) mergeFrom:(P2CMsgReadReq*) other;
- (P2CMsgReadReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CMsgReadReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (P2CMsgReadReqBuilder*) setUserid:(NSString*) value;
- (P2CMsgReadReqBuilder*) clearUserid;

- (BOOL) hasMsgid;
- (NSString*) msgid;
- (P2CMsgReadReqBuilder*) setMsgid:(NSString*) value;
- (P2CMsgReadReqBuilder*) clearMsgid;
@end

#define P2CMsgReadRsp_userid @"userid"
#define P2CMsgReadRsp_code @"code"
@interface P2CMsgReadRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CMsgReadRspBuilder*) builder;
+ (P2CMsgReadRspBuilder*) builder;
+ (P2CMsgReadRspBuilder*) builderWithPrototype:(P2CMsgReadRsp*) prototype;
- (P2CMsgReadRspBuilder*) toBuilder;

+ (P2CMsgReadRsp*) parseFromData:(NSData*) data;
+ (P2CMsgReadRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgReadRsp*) parseFromInputStream:(NSInputStream*) input;
+ (P2CMsgReadRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CMsgReadRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CMsgReadRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CMsgReadRspBuilder : PBGeneratedMessageBuilder {
@private
  P2CMsgReadRsp* resultP2CmsgReadRsp;
}

- (P2CMsgReadRsp*) defaultInstance;

- (P2CMsgReadRspBuilder*) clear;
- (P2CMsgReadRspBuilder*) clone;

- (P2CMsgReadRsp*) build;
- (P2CMsgReadRsp*) buildPartial;

- (P2CMsgReadRspBuilder*) mergeFrom:(P2CMsgReadRsp*) other;
- (P2CMsgReadRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CMsgReadRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (P2CMsgReadRspBuilder*) setUserid:(NSString*) value;
- (P2CMsgReadRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (P2CMsgReadRspBuilder*) setCode:(ResultCode) value;
- (P2CMsgReadRspBuilder*) clearCode;
@end

#define P2CSwitchEntity_consumerid @"consumerid"
#define P2CSwitchEntity_newkefuid @"newkefuid"
#define P2CSwitchEntity_oldkefuid @"oldkefuid"
#define P2CSwitchEntity_sessionid @"sessionid"
#define P2CSwitchEntity_content @"content"
@interface P2CSwitchEntity : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasConsumerid_:1;
  BOOL hasNewkefuid_:1;
  BOOL hasOldkefuid_:1;
  BOOL hasSessionid_:1;
  BOOL hasContent_:1;
  NSString* consumerid;
  NSString* newkefuid;
  NSString* oldkefuid;
  NSString* sessionid;
  NSString* content;
}
- (BOOL) hasConsumerid;
- (BOOL) hasNewkefuid;
- (BOOL) hasOldkefuid;
- (BOOL) hasSessionid;
- (BOOL) hasContent;
@property (readonly, strong) NSString* consumerid;
@property (readonly, strong) NS_RETURNS_NOT_RETAINED NSString* newkefuid;
@property (readonly, strong) NSString* oldkefuid;
@property (readonly, strong) NSString* sessionid;
@property (readonly, strong) NSString* content;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CSwitchEntityBuilder*) builder;
+ (P2CSwitchEntityBuilder*) builder;
+ (P2CSwitchEntityBuilder*) builderWithPrototype:(P2CSwitchEntity*) prototype;
- (P2CSwitchEntityBuilder*) toBuilder;

+ (P2CSwitchEntity*) parseFromData:(NSData*) data;
+ (P2CSwitchEntity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CSwitchEntity*) parseFromInputStream:(NSInputStream*) input;
+ (P2CSwitchEntity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CSwitchEntity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CSwitchEntity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CSwitchEntityBuilder : PBGeneratedMessageBuilder {
@private
  P2CSwitchEntity* resultP2CswitchEntity;
}

- (P2CSwitchEntity*) defaultInstance;

- (P2CSwitchEntityBuilder*) clear;
- (P2CSwitchEntityBuilder*) clone;

- (P2CSwitchEntity*) build;
- (P2CSwitchEntity*) buildPartial;

- (P2CSwitchEntityBuilder*) mergeFrom:(P2CSwitchEntity*) other;
- (P2CSwitchEntityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CSwitchEntityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasConsumerid;
- (NSString*) consumerid;
- (P2CSwitchEntityBuilder*) setConsumerid:(NSString*) value;
- (P2CSwitchEntityBuilder*) clearConsumerid;

- (BOOL) hasNewkefuid;
- (NSString*) newkefuid NS_RETURNS_NOT_RETAINED;
- (P2CSwitchEntityBuilder*) setNewkefuid:(NSString*) value;
- (P2CSwitchEntityBuilder*) clearNewkefuid;

- (BOOL) hasOldkefuid;
- (NSString*) oldkefuid;
- (P2CSwitchEntityBuilder*) setOldkefuid:(NSString*) value;
- (P2CSwitchEntityBuilder*) clearOldkefuid;

- (BOOL) hasSessionid;
- (NSString*) sessionid;
- (P2CSwitchEntityBuilder*) setSessionid:(NSString*) value;
- (P2CSwitchEntityBuilder*) clearSessionid;

- (BOOL) hasContent;
- (NSString*) content;
- (P2CSwitchEntityBuilder*) setContent:(NSString*) value;
- (P2CSwitchEntityBuilder*) clearContent;
@end

#define SwitchP2CReq_element @"element"
#define SwitchP2CReq_greeting @"greeting"
#define SwitchP2CReq_resptime @"resptime"
@interface SwitchP2CReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasResptime_:1;
  BOOL hasGreeting_:1;
  BOOL hasElement_:1;
  UInt64 resptime;
  NSString* greeting;
  P2CSwitchEntity* element;
}
- (BOOL) hasElement;
- (BOOL) hasGreeting;
- (BOOL) hasResptime;
@property (readonly, strong) P2CSwitchEntity* element;
@property (readonly, strong) NSString* greeting;
@property (readonly) UInt64 resptime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SwitchP2CReqBuilder*) builder;
+ (SwitchP2CReqBuilder*) builder;
+ (SwitchP2CReqBuilder*) builderWithPrototype:(SwitchP2CReq*) prototype;
- (SwitchP2CReqBuilder*) toBuilder;

+ (SwitchP2CReq*) parseFromData:(NSData*) data;
+ (SwitchP2CReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwitchP2CReq*) parseFromInputStream:(NSInputStream*) input;
+ (SwitchP2CReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwitchP2CReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SwitchP2CReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SwitchP2CReqBuilder : PBGeneratedMessageBuilder {
@private
  SwitchP2CReq* resultSwitchP2Creq;
}

- (SwitchP2CReq*) defaultInstance;

- (SwitchP2CReqBuilder*) clear;
- (SwitchP2CReqBuilder*) clone;

- (SwitchP2CReq*) build;
- (SwitchP2CReq*) buildPartial;

- (SwitchP2CReqBuilder*) mergeFrom:(SwitchP2CReq*) other;
- (SwitchP2CReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SwitchP2CReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasElement;
- (P2CSwitchEntity*) element;
- (SwitchP2CReqBuilder*) setElement:(P2CSwitchEntity*) value;
- (SwitchP2CReqBuilder*) setElementBuilder:(P2CSwitchEntityBuilder*) builderForValue;
- (SwitchP2CReqBuilder*) mergeElement:(P2CSwitchEntity*) value;
- (SwitchP2CReqBuilder*) clearElement;

- (BOOL) hasGreeting;
- (NSString*) greeting;
- (SwitchP2CReqBuilder*) setGreeting:(NSString*) value;
- (SwitchP2CReqBuilder*) clearGreeting;

- (BOOL) hasResptime;
- (UInt64) resptime;
- (SwitchP2CReqBuilder*) setResptime:(UInt64) value;
- (SwitchP2CReqBuilder*) clearResptime;
@end

#define SwitchP2CRsp_element @"element"
#define SwitchP2CRsp_code @"code"
@interface SwitchP2CRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasElement_:1;
  BOOL hasCode_:1;
  P2CSwitchEntity* element;
  ResultCode code;
}
- (BOOL) hasElement;
- (BOOL) hasCode;
@property (readonly, strong) P2CSwitchEntity* element;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SwitchP2CRspBuilder*) builder;
+ (SwitchP2CRspBuilder*) builder;
+ (SwitchP2CRspBuilder*) builderWithPrototype:(SwitchP2CRsp*) prototype;
- (SwitchP2CRspBuilder*) toBuilder;

+ (SwitchP2CRsp*) parseFromData:(NSData*) data;
+ (SwitchP2CRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwitchP2CRsp*) parseFromInputStream:(NSInputStream*) input;
+ (SwitchP2CRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwitchP2CRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SwitchP2CRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SwitchP2CRspBuilder : PBGeneratedMessageBuilder {
@private
  SwitchP2CRsp* resultSwitchP2Crsp;
}

- (SwitchP2CRsp*) defaultInstance;

- (SwitchP2CRspBuilder*) clear;
- (SwitchP2CRspBuilder*) clone;

- (SwitchP2CRsp*) build;
- (SwitchP2CRsp*) buildPartial;

- (SwitchP2CRspBuilder*) mergeFrom:(SwitchP2CRsp*) other;
- (SwitchP2CRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SwitchP2CRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasElement;
- (P2CSwitchEntity*) element;
- (SwitchP2CRspBuilder*) setElement:(P2CSwitchEntity*) value;
- (SwitchP2CRspBuilder*) setElementBuilder:(P2CSwitchEntityBuilder*) builderForValue;
- (SwitchP2CRspBuilder*) mergeElement:(P2CSwitchEntity*) value;
- (SwitchP2CRspBuilder*) clearElement;

- (BOOL) hasCode;
- (ResultCode) code;
- (SwitchP2CRspBuilder*) setCode:(ResultCode) value;
- (SwitchP2CRspBuilder*) clearCode;
@end

#define NotifySwitchP2C_element @"element"
#define NotifySwitchP2C_greeting @"greeting"
#define NotifySwitchP2C_resptime @"resptime"
@interface NotifySwitchP2C : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasResptime_:1;
  BOOL hasGreeting_:1;
  BOOL hasElement_:1;
  UInt64 resptime;
  NSString* greeting;
  P2CSwitchEntity* element;
}
- (BOOL) hasElement;
- (BOOL) hasGreeting;
- (BOOL) hasResptime;
@property (readonly, strong) P2CSwitchEntity* element;
@property (readonly, strong) NSString* greeting;
@property (readonly) UInt64 resptime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (NotifySwitchP2CBuilder*) builder;
+ (NotifySwitchP2CBuilder*) builder;
+ (NotifySwitchP2CBuilder*) builderWithPrototype:(NotifySwitchP2C*) prototype;
- (NotifySwitchP2CBuilder*) toBuilder;

+ (NotifySwitchP2C*) parseFromData:(NSData*) data;
+ (NotifySwitchP2C*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NotifySwitchP2C*) parseFromInputStream:(NSInputStream*) input;
+ (NotifySwitchP2C*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NotifySwitchP2C*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (NotifySwitchP2C*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface NotifySwitchP2CBuilder : PBGeneratedMessageBuilder {
@private
  NotifySwitchP2C* resultNotifySwitchP2C;
}

- (NotifySwitchP2C*) defaultInstance;

- (NotifySwitchP2CBuilder*) clear;
- (NotifySwitchP2CBuilder*) clone;

- (NotifySwitchP2C*) build;
- (NotifySwitchP2C*) buildPartial;

- (NotifySwitchP2CBuilder*) mergeFrom:(NotifySwitchP2C*) other;
- (NotifySwitchP2CBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (NotifySwitchP2CBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasElement;
- (P2CSwitchEntity*) element;
- (NotifySwitchP2CBuilder*) setElement:(P2CSwitchEntity*) value;
- (NotifySwitchP2CBuilder*) setElementBuilder:(P2CSwitchEntityBuilder*) builderForValue;
- (NotifySwitchP2CBuilder*) mergeElement:(P2CSwitchEntity*) value;
- (NotifySwitchP2CBuilder*) clearElement;

- (BOOL) hasGreeting;
- (NSString*) greeting;
- (NotifySwitchP2CBuilder*) setGreeting:(NSString*) value;
- (NotifySwitchP2CBuilder*) clearGreeting;

- (BOOL) hasResptime;
- (UInt64) resptime;
- (NotifySwitchP2CBuilder*) setResptime:(UInt64) value;
- (NotifySwitchP2CBuilder*) clearResptime;
@end

#define NotifySwitchP2CRsp_element @"element"
#define NotifySwitchP2CRsp_code @"code"
@interface NotifySwitchP2CRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasElement_:1;
  BOOL hasCode_:1;
  P2CSwitchEntity* element;
  ResultCode code;
}
- (BOOL) hasElement;
- (BOOL) hasCode;
@property (readonly, strong) P2CSwitchEntity* element;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (NotifySwitchP2CRspBuilder*) builder;
+ (NotifySwitchP2CRspBuilder*) builder;
+ (NotifySwitchP2CRspBuilder*) builderWithPrototype:(NotifySwitchP2CRsp*) prototype;
- (NotifySwitchP2CRspBuilder*) toBuilder;

+ (NotifySwitchP2CRsp*) parseFromData:(NSData*) data;
+ (NotifySwitchP2CRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NotifySwitchP2CRsp*) parseFromInputStream:(NSInputStream*) input;
+ (NotifySwitchP2CRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NotifySwitchP2CRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (NotifySwitchP2CRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface NotifySwitchP2CRspBuilder : PBGeneratedMessageBuilder {
@private
  NotifySwitchP2CRsp* resultNotifySwitchP2Crsp;
}

- (NotifySwitchP2CRsp*) defaultInstance;

- (NotifySwitchP2CRspBuilder*) clear;
- (NotifySwitchP2CRspBuilder*) clone;

- (NotifySwitchP2CRsp*) build;
- (NotifySwitchP2CRsp*) buildPartial;

- (NotifySwitchP2CRspBuilder*) mergeFrom:(NotifySwitchP2CRsp*) other;
- (NotifySwitchP2CRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (NotifySwitchP2CRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasElement;
- (P2CSwitchEntity*) element;
- (NotifySwitchP2CRspBuilder*) setElement:(P2CSwitchEntity*) value;
- (NotifySwitchP2CRspBuilder*) setElementBuilder:(P2CSwitchEntityBuilder*) builderForValue;
- (NotifySwitchP2CRspBuilder*) mergeElement:(P2CSwitchEntity*) value;
- (NotifySwitchP2CRspBuilder*) clearElement;

- (BOOL) hasCode;
- (ResultCode) code;
- (NotifySwitchP2CRspBuilder*) setCode:(ResultCode) value;
- (NotifySwitchP2CRspBuilder*) clearCode;
@end

#define P2CLeaveMsgReq_fromid @"fromid"
#define P2CLeaveMsgReq_entid @"entid"
#define P2CLeaveMsgReq_sessionid @"sessionid"
#define P2CLeaveMsgReq_content @"content"
#define P2CLeaveMsgReq_guid @"guid"
@interface P2CLeaveMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFromid_:1;
  BOOL hasEntid_:1;
  BOOL hasSessionid_:1;
  BOOL hasContent_:1;
  BOOL hasGuid_:1;
  NSString* fromid;
  NSString* entid;
  NSString* sessionid;
  NSString* content;
  NSString* guid;
}
- (BOOL) hasFromid;
- (BOOL) hasEntid;
- (BOOL) hasSessionid;
- (BOOL) hasContent;
- (BOOL) hasGuid;
@property (readonly, strong) NSString* fromid;
@property (readonly, strong) NSString* entid;
@property (readonly, strong) NSString* sessionid;
@property (readonly, strong) NSString* content;
@property (readonly, strong) NSString* guid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CLeaveMsgReqBuilder*) builder;
+ (P2CLeaveMsgReqBuilder*) builder;
+ (P2CLeaveMsgReqBuilder*) builderWithPrototype:(P2CLeaveMsgReq*) prototype;
- (P2CLeaveMsgReqBuilder*) toBuilder;

+ (P2CLeaveMsgReq*) parseFromData:(NSData*) data;
+ (P2CLeaveMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CLeaveMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (P2CLeaveMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CLeaveMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CLeaveMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CLeaveMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  P2CLeaveMsgReq* resultP2CleaveMsgReq;
}

- (P2CLeaveMsgReq*) defaultInstance;

- (P2CLeaveMsgReqBuilder*) clear;
- (P2CLeaveMsgReqBuilder*) clone;

- (P2CLeaveMsgReq*) build;
- (P2CLeaveMsgReq*) buildPartial;

- (P2CLeaveMsgReqBuilder*) mergeFrom:(P2CLeaveMsgReq*) other;
- (P2CLeaveMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CLeaveMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromid;
- (NSString*) fromid;
- (P2CLeaveMsgReqBuilder*) setFromid:(NSString*) value;
- (P2CLeaveMsgReqBuilder*) clearFromid;

- (BOOL) hasEntid;
- (NSString*) entid;
- (P2CLeaveMsgReqBuilder*) setEntid:(NSString*) value;
- (P2CLeaveMsgReqBuilder*) clearEntid;

- (BOOL) hasSessionid;
- (NSString*) sessionid;
- (P2CLeaveMsgReqBuilder*) setSessionid:(NSString*) value;
- (P2CLeaveMsgReqBuilder*) clearSessionid;

- (BOOL) hasContent;
- (NSString*) content;
- (P2CLeaveMsgReqBuilder*) setContent:(NSString*) value;
- (P2CLeaveMsgReqBuilder*) clearContent;

- (BOOL) hasGuid;
- (NSString*) guid;
- (P2CLeaveMsgReqBuilder*) setGuid:(NSString*) value;
- (P2CLeaveMsgReqBuilder*) clearGuid;
@end

#define P2CLeaveMsgRsp_userid @"userid"
#define P2CLeaveMsgRsp_guid @"guid"
#define P2CLeaveMsgRsp_code @"code"
@interface P2CLeaveMsgRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasGuid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  NSString* guid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasGuid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSString* guid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2CLeaveMsgRspBuilder*) builder;
+ (P2CLeaveMsgRspBuilder*) builder;
+ (P2CLeaveMsgRspBuilder*) builderWithPrototype:(P2CLeaveMsgRsp*) prototype;
- (P2CLeaveMsgRspBuilder*) toBuilder;

+ (P2CLeaveMsgRsp*) parseFromData:(NSData*) data;
+ (P2CLeaveMsgRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CLeaveMsgRsp*) parseFromInputStream:(NSInputStream*) input;
+ (P2CLeaveMsgRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2CLeaveMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2CLeaveMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2CLeaveMsgRspBuilder : PBGeneratedMessageBuilder {
@private
  P2CLeaveMsgRsp* resultP2CleaveMsgRsp;
}

- (P2CLeaveMsgRsp*) defaultInstance;

- (P2CLeaveMsgRspBuilder*) clear;
- (P2CLeaveMsgRspBuilder*) clone;

- (P2CLeaveMsgRsp*) build;
- (P2CLeaveMsgRsp*) buildPartial;

- (P2CLeaveMsgRspBuilder*) mergeFrom:(P2CLeaveMsgRsp*) other;
- (P2CLeaveMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2CLeaveMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (P2CLeaveMsgRspBuilder*) setUserid:(NSString*) value;
- (P2CLeaveMsgRspBuilder*) clearUserid;

- (BOOL) hasGuid;
- (NSString*) guid;
- (P2CLeaveMsgRspBuilder*) setGuid:(NSString*) value;
- (P2CLeaveMsgRspBuilder*) clearGuid;

- (BOOL) hasCode;
- (ResultCode) code;
- (P2CLeaveMsgRspBuilder*) setCode:(ResultCode) value;
- (P2CLeaveMsgRspBuilder*) clearCode;
@end

#define P2COfflineMsgReq_category @"category"
#define P2COfflineMsgReq_fromid @"fromid"
#define P2COfflineMsgReq_toid @"toid"
#define P2COfflineMsgReq_count @"count"
#define P2COfflineMsgReq_lastupdate @"lastupdate"
@interface P2COfflineMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLastupdate_:1;
  BOOL hasCount_:1;
  BOOL hasCategory_:1;
  BOOL hasFromid_:1;
  BOOL hasToid_:1;
  UInt64 lastupdate;
  SInt32 count;
  NSString* category;
  NSString* fromid;
  NSString* toid;
}
- (BOOL) hasCategory;
- (BOOL) hasFromid;
- (BOOL) hasToid;
- (BOOL) hasCount;
- (BOOL) hasLastupdate;
@property (readonly, strong) NSString* category;
@property (readonly, strong) NSString* fromid;
@property (readonly, strong) NSString* toid;
@property (readonly) SInt32 count;
@property (readonly) UInt64 lastupdate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2COfflineMsgReqBuilder*) builder;
+ (P2COfflineMsgReqBuilder*) builder;
+ (P2COfflineMsgReqBuilder*) builderWithPrototype:(P2COfflineMsgReq*) prototype;
- (P2COfflineMsgReqBuilder*) toBuilder;

+ (P2COfflineMsgReq*) parseFromData:(NSData*) data;
+ (P2COfflineMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2COfflineMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (P2COfflineMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2COfflineMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2COfflineMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2COfflineMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  P2COfflineMsgReq* resultP2CofflineMsgReq;
}

- (P2COfflineMsgReq*) defaultInstance;

- (P2COfflineMsgReqBuilder*) clear;
- (P2COfflineMsgReqBuilder*) clone;

- (P2COfflineMsgReq*) build;
- (P2COfflineMsgReq*) buildPartial;

- (P2COfflineMsgReqBuilder*) mergeFrom:(P2COfflineMsgReq*) other;
- (P2COfflineMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2COfflineMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCategory;
- (NSString*) category;
- (P2COfflineMsgReqBuilder*) setCategory:(NSString*) value;
- (P2COfflineMsgReqBuilder*) clearCategory;

- (BOOL) hasFromid;
- (NSString*) fromid;
- (P2COfflineMsgReqBuilder*) setFromid:(NSString*) value;
- (P2COfflineMsgReqBuilder*) clearFromid;

- (BOOL) hasToid;
- (NSString*) toid;
- (P2COfflineMsgReqBuilder*) setToid:(NSString*) value;
- (P2COfflineMsgReqBuilder*) clearToid;

- (BOOL) hasCount;
- (SInt32) count;
- (P2COfflineMsgReqBuilder*) setCount:(SInt32) value;
- (P2COfflineMsgReqBuilder*) clearCount;

- (BOOL) hasLastupdate;
- (UInt64) lastupdate;
- (P2COfflineMsgReqBuilder*) setLastupdate:(UInt64) value;
- (P2COfflineMsgReqBuilder*) clearLastupdate;
@end

#define P2COfflineMsgRsp_userid @"userid"
#define P2COfflineMsgRsp_msglist @"msglist"
#define P2COfflineMsgRsp_code @"code"
@interface P2COfflineMsgRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
  NSMutableArray * msglistArray;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly, strong) NSArray<P2CMsg*> * msglist;
@property (readonly) ResultCode code;
- (P2CMsg*)msglistAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (P2COfflineMsgRspBuilder*) builder;
+ (P2COfflineMsgRspBuilder*) builder;
+ (P2COfflineMsgRspBuilder*) builderWithPrototype:(P2COfflineMsgRsp*) prototype;
- (P2COfflineMsgRspBuilder*) toBuilder;

+ (P2COfflineMsgRsp*) parseFromData:(NSData*) data;
+ (P2COfflineMsgRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2COfflineMsgRsp*) parseFromInputStream:(NSInputStream*) input;
+ (P2COfflineMsgRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (P2COfflineMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (P2COfflineMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface P2COfflineMsgRspBuilder : PBGeneratedMessageBuilder {
@private
  P2COfflineMsgRsp* resultP2CofflineMsgRsp;
}

- (P2COfflineMsgRsp*) defaultInstance;

- (P2COfflineMsgRspBuilder*) clear;
- (P2COfflineMsgRspBuilder*) clone;

- (P2COfflineMsgRsp*) build;
- (P2COfflineMsgRsp*) buildPartial;

- (P2COfflineMsgRspBuilder*) mergeFrom:(P2COfflineMsgRsp*) other;
- (P2COfflineMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (P2COfflineMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (P2COfflineMsgRspBuilder*) setUserid:(NSString*) value;
- (P2COfflineMsgRspBuilder*) clearUserid;

- (NSMutableArray<P2CMsg*> *)msglist;
- (P2CMsg*)msglistAtIndex:(NSUInteger)index;
- (P2COfflineMsgRspBuilder *)addMsglist:(P2CMsg*)value;
- (P2COfflineMsgRspBuilder *)setMsglistArray:(NSArray<P2CMsg*> *)array;
- (P2COfflineMsgRspBuilder *)clearMsglist;

- (BOOL) hasCode;
- (ResultCode) code;
- (P2COfflineMsgRspBuilder*) setCode:(ResultCode) value;
- (P2COfflineMsgRspBuilder*) clearCode;
@end

#define AssignP2CLeaveMsgReq_fromid @"fromid"
#define AssignP2CLeaveMsgReq_entid @"entid"
@interface AssignP2CLeaveMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFromid_:1;
  BOOL hasEntid_:1;
  NSString* fromid;
  NSString* entid;
}
- (BOOL) hasFromid;
- (BOOL) hasEntid;
@property (readonly, strong) NSString* fromid;
@property (readonly, strong) NSString* entid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AssignP2CLeaveMsgReqBuilder*) builder;
+ (AssignP2CLeaveMsgReqBuilder*) builder;
+ (AssignP2CLeaveMsgReqBuilder*) builderWithPrototype:(AssignP2CLeaveMsgReq*) prototype;
- (AssignP2CLeaveMsgReqBuilder*) toBuilder;

+ (AssignP2CLeaveMsgReq*) parseFromData:(NSData*) data;
+ (AssignP2CLeaveMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AssignP2CLeaveMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (AssignP2CLeaveMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AssignP2CLeaveMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AssignP2CLeaveMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AssignP2CLeaveMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  AssignP2CLeaveMsgReq* resultAssignP2CleaveMsgReq;
}

- (AssignP2CLeaveMsgReq*) defaultInstance;

- (AssignP2CLeaveMsgReqBuilder*) clear;
- (AssignP2CLeaveMsgReqBuilder*) clone;

- (AssignP2CLeaveMsgReq*) build;
- (AssignP2CLeaveMsgReq*) buildPartial;

- (AssignP2CLeaveMsgReqBuilder*) mergeFrom:(AssignP2CLeaveMsgReq*) other;
- (AssignP2CLeaveMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AssignP2CLeaveMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromid;
- (NSString*) fromid;
- (AssignP2CLeaveMsgReqBuilder*) setFromid:(NSString*) value;
- (AssignP2CLeaveMsgReqBuilder*) clearFromid;

- (BOOL) hasEntid;
- (NSString*) entid;
- (AssignP2CLeaveMsgReqBuilder*) setEntid:(NSString*) value;
- (AssignP2CLeaveMsgReqBuilder*) clearEntid;
@end

#define AssignP2CLeaveMsgRsp_userid @"userid"
#define AssignP2CLeaveMsgRsp_code @"code"
@interface AssignP2CLeaveMsgRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  BOOL hasCode_:1;
  NSString* userid;
  ResultCode code;
}
- (BOOL) hasUserid;
- (BOOL) hasCode;
@property (readonly, strong) NSString* userid;
@property (readonly) ResultCode code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AssignP2CLeaveMsgRspBuilder*) builder;
+ (AssignP2CLeaveMsgRspBuilder*) builder;
+ (AssignP2CLeaveMsgRspBuilder*) builderWithPrototype:(AssignP2CLeaveMsgRsp*) prototype;
- (AssignP2CLeaveMsgRspBuilder*) toBuilder;

+ (AssignP2CLeaveMsgRsp*) parseFromData:(NSData*) data;
+ (AssignP2CLeaveMsgRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AssignP2CLeaveMsgRsp*) parseFromInputStream:(NSInputStream*) input;
+ (AssignP2CLeaveMsgRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AssignP2CLeaveMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AssignP2CLeaveMsgRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AssignP2CLeaveMsgRspBuilder : PBGeneratedMessageBuilder {
@private
  AssignP2CLeaveMsgRsp* resultAssignP2CleaveMsgRsp;
}

- (AssignP2CLeaveMsgRsp*) defaultInstance;

- (AssignP2CLeaveMsgRspBuilder*) clear;
- (AssignP2CLeaveMsgRspBuilder*) clone;

- (AssignP2CLeaveMsgRsp*) build;
- (AssignP2CLeaveMsgRsp*) buildPartial;

- (AssignP2CLeaveMsgRspBuilder*) mergeFrom:(AssignP2CLeaveMsgRsp*) other;
- (AssignP2CLeaveMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AssignP2CLeaveMsgRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (AssignP2CLeaveMsgRspBuilder*) setUserid:(NSString*) value;
- (AssignP2CLeaveMsgRspBuilder*) clearUserid;

- (BOOL) hasCode;
- (ResultCode) code;
- (AssignP2CLeaveMsgRspBuilder*) setCode:(ResultCode) value;
- (AssignP2CLeaveMsgRspBuilder*) clearCode;
@end


// @@protoc_insertion_point(global_scope)
