// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ImHxapns.pb.h"
// @@protoc_insertion_point(imports)

@implementation ImHxapnsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ImHxapnsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [ImHxcommonRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface ApnsPushReq ()
@property (strong) NSString* deviceVersion;
@property (strong) NSString* token;
@property (strong) NSString* msgid;
@property (strong) NSString* toid;
@end

@implementation ApnsPushReq

- (BOOL) hasDeviceVersion {
  return !!hasDeviceVersion_;
}
- (void) setHasDeviceVersion:(BOOL) _value_ {
  hasDeviceVersion_ = !!_value_;
}
@synthesize deviceVersion;
- (BOOL) hasToken {
  return !!hasToken_;
}
- (void) setHasToken:(BOOL) _value_ {
  hasToken_ = !!_value_;
}
@synthesize token;
- (BOOL) hasMsgid {
  return !!hasMsgid_;
}
- (void) setHasMsgid:(BOOL) _value_ {
  hasMsgid_ = !!_value_;
}
@synthesize msgid;
- (BOOL) hasToid {
  return !!hasToid_;
}
- (void) setHasToid:(BOOL) _value_ {
  hasToid_ = !!_value_;
}
@synthesize toid;
- (instancetype) init {
  if ((self = [super init])) {
    self.deviceVersion = @"";
    self.token = @"";
    self.msgid = @"";
    self.toid = @"";
  }
  return self;
}
static ApnsPushReq* defaultApnsPushReqInstance = nil;
+ (void) initialize {
  if (self == [ApnsPushReq class]) {
    defaultApnsPushReqInstance = [[ApnsPushReq alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultApnsPushReqInstance;
}
- (instancetype) defaultInstance {
  return defaultApnsPushReqInstance;
}
- (BOOL) isInitialized {
  if (!self.hasDeviceVersion) {
    return NO;
  }
  if (!self.hasToken) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasDeviceVersion) {
    [output writeString:1 value:self.deviceVersion];
  }
  if (self.hasToken) {
    [output writeString:2 value:self.token];
  }
  if (self.hasMsgid) {
    [output writeString:3 value:self.msgid];
  }
  if (self.hasToid) {
    [output writeString:4 value:self.toid];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasDeviceVersion) {
    size_ += computeStringSize(1, self.deviceVersion);
  }
  if (self.hasToken) {
    size_ += computeStringSize(2, self.token);
  }
  if (self.hasMsgid) {
    size_ += computeStringSize(3, self.msgid);
  }
  if (self.hasToid) {
    size_ += computeStringSize(4, self.toid);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ApnsPushReq*) parseFromData:(NSData*) data {
  return (ApnsPushReq*)[[[ApnsPushReq builder] mergeFromData:data] build];
}
+ (ApnsPushReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ApnsPushReq*)[[[ApnsPushReq builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ApnsPushReq*) parseFromInputStream:(NSInputStream*) input {
  return (ApnsPushReq*)[[[ApnsPushReq builder] mergeFromInputStream:input] build];
}
+ (ApnsPushReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ApnsPushReq*)[[[ApnsPushReq builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ApnsPushReq*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ApnsPushReq*)[[[ApnsPushReq builder] mergeFromCodedInputStream:input] build];
}
+ (ApnsPushReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ApnsPushReq*)[[[ApnsPushReq builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ApnsPushReqBuilder*) builder {
  return [[ApnsPushReqBuilder alloc] init];
}
+ (ApnsPushReqBuilder*) builderWithPrototype:(ApnsPushReq*) prototype {
  return [[ApnsPushReq builder] mergeFrom:prototype];
}
- (ApnsPushReqBuilder*) builder {
  return [ApnsPushReq builder];
}
- (ApnsPushReqBuilder*) toBuilder {
  return [ApnsPushReq builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasDeviceVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"deviceVersion", self.deviceVersion];
  }
  if (self.hasToken) {
    [output appendFormat:@"%@%@: %@\n", indent, @"token", self.token];
  }
  if (self.hasMsgid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"msgid", self.msgid];
  }
  if (self.hasToid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"toid", self.toid];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasDeviceVersion) {
    [dictionary setObject: self.deviceVersion forKey: @"deviceVersion"];
  }
  if (self.hasToken) {
    [dictionary setObject: self.token forKey: @"token"];
  }
  if (self.hasMsgid) {
    [dictionary setObject: self.msgid forKey: @"msgid"];
  }
  if (self.hasToid) {
    [dictionary setObject: self.toid forKey: @"toid"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ApnsPushReq class]]) {
    return NO;
  }
  ApnsPushReq *otherMessage = other;
  return
      self.hasDeviceVersion == otherMessage.hasDeviceVersion &&
      (!self.hasDeviceVersion || [self.deviceVersion isEqual:otherMessage.deviceVersion]) &&
      self.hasToken == otherMessage.hasToken &&
      (!self.hasToken || [self.token isEqual:otherMessage.token]) &&
      self.hasMsgid == otherMessage.hasMsgid &&
      (!self.hasMsgid || [self.msgid isEqual:otherMessage.msgid]) &&
      self.hasToid == otherMessage.hasToid &&
      (!self.hasToid || [self.toid isEqual:otherMessage.toid]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasDeviceVersion) {
    hashCode = hashCode * 31 + [self.deviceVersion hash];
  }
  if (self.hasToken) {
    hashCode = hashCode * 31 + [self.token hash];
  }
  if (self.hasMsgid) {
    hashCode = hashCode * 31 + [self.msgid hash];
  }
  if (self.hasToid) {
    hashCode = hashCode * 31 + [self.toid hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ApnsPushReqBuilder()
@property (strong) ApnsPushReq* resultApnsPushReq;
@end

@implementation ApnsPushReqBuilder
@synthesize resultApnsPushReq;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultApnsPushReq = [[ApnsPushReq alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultApnsPushReq;
}
- (ApnsPushReqBuilder*) clear {
  self.resultApnsPushReq = [[ApnsPushReq alloc] init];
  return self;
}
- (ApnsPushReqBuilder*) clone {
  return [ApnsPushReq builderWithPrototype:resultApnsPushReq];
}
- (ApnsPushReq*) defaultInstance {
  return [ApnsPushReq defaultInstance];
}
- (ApnsPushReq*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ApnsPushReq*) buildPartial {
  ApnsPushReq* returnMe = resultApnsPushReq;
  self.resultApnsPushReq = nil;
  return returnMe;
}
- (ApnsPushReqBuilder*) mergeFrom:(ApnsPushReq*) other {
  if (other == [ApnsPushReq defaultInstance]) {
    return self;
  }
  if (other.hasDeviceVersion) {
    [self setDeviceVersion:other.deviceVersion];
  }
  if (other.hasToken) {
    [self setToken:other.token];
  }
  if (other.hasMsgid) {
    [self setMsgid:other.msgid];
  }
  if (other.hasToid) {
    [self setToid:other.toid];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ApnsPushReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ApnsPushReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setDeviceVersion:[input readString]];
        break;
      }
      case 18: {
        [self setToken:[input readString]];
        break;
      }
      case 26: {
        [self setMsgid:[input readString]];
        break;
      }
      case 34: {
        [self setToid:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasDeviceVersion {
  return resultApnsPushReq.hasDeviceVersion;
}
- (NSString*) deviceVersion {
  return resultApnsPushReq.deviceVersion;
}
- (ApnsPushReqBuilder*) setDeviceVersion:(NSString*) value {
  resultApnsPushReq.hasDeviceVersion = YES;
  resultApnsPushReq.deviceVersion = value;
  return self;
}
- (ApnsPushReqBuilder*) clearDeviceVersion {
  resultApnsPushReq.hasDeviceVersion = NO;
  resultApnsPushReq.deviceVersion = @"";
  return self;
}
- (BOOL) hasToken {
  return resultApnsPushReq.hasToken;
}
- (NSString*) token {
  return resultApnsPushReq.token;
}
- (ApnsPushReqBuilder*) setToken:(NSString*) value {
  resultApnsPushReq.hasToken = YES;
  resultApnsPushReq.token = value;
  return self;
}
- (ApnsPushReqBuilder*) clearToken {
  resultApnsPushReq.hasToken = NO;
  resultApnsPushReq.token = @"";
  return self;
}
- (BOOL) hasMsgid {
  return resultApnsPushReq.hasMsgid;
}
- (NSString*) msgid {
  return resultApnsPushReq.msgid;
}
- (ApnsPushReqBuilder*) setMsgid:(NSString*) value {
  resultApnsPushReq.hasMsgid = YES;
  resultApnsPushReq.msgid = value;
  return self;
}
- (ApnsPushReqBuilder*) clearMsgid {
  resultApnsPushReq.hasMsgid = NO;
  resultApnsPushReq.msgid = @"";
  return self;
}
- (BOOL) hasToid {
  return resultApnsPushReq.hasToid;
}
- (NSString*) toid {
  return resultApnsPushReq.toid;
}
- (ApnsPushReqBuilder*) setToid:(NSString*) value {
  resultApnsPushReq.hasToid = YES;
  resultApnsPushReq.toid = value;
  return self;
}
- (ApnsPushReqBuilder*) clearToid {
  resultApnsPushReq.hasToid = NO;
  resultApnsPushReq.toid = @"";
  return self;
}
@end

@interface ApnsPushRsp ()
@property ResultCode code;
@end

@implementation ApnsPushRsp

- (BOOL) hasCode {
  return !!hasCode_;
}
- (void) setHasCode:(BOOL) _value_ {
  hasCode_ = !!_value_;
}
@synthesize code;
- (instancetype) init {
  if ((self = [super init])) {
    self.code = ResultCodeNoError;
  }
  return self;
}
static ApnsPushRsp* defaultApnsPushRspInstance = nil;
+ (void) initialize {
  if (self == [ApnsPushRsp class]) {
    defaultApnsPushRspInstance = [[ApnsPushRsp alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultApnsPushRspInstance;
}
- (instancetype) defaultInstance {
  return defaultApnsPushRspInstance;
}
- (BOOL) isInitialized {
  if (!self.hasCode) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCode) {
    [output writeEnum:1 value:self.code];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasCode) {
    size_ += computeEnumSize(1, self.code);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ApnsPushRsp*) parseFromData:(NSData*) data {
  return (ApnsPushRsp*)[[[ApnsPushRsp builder] mergeFromData:data] build];
}
+ (ApnsPushRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ApnsPushRsp*)[[[ApnsPushRsp builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ApnsPushRsp*) parseFromInputStream:(NSInputStream*) input {
  return (ApnsPushRsp*)[[[ApnsPushRsp builder] mergeFromInputStream:input] build];
}
+ (ApnsPushRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ApnsPushRsp*)[[[ApnsPushRsp builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ApnsPushRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ApnsPushRsp*)[[[ApnsPushRsp builder] mergeFromCodedInputStream:input] build];
}
+ (ApnsPushRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ApnsPushRsp*)[[[ApnsPushRsp builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ApnsPushRspBuilder*) builder {
  return [[ApnsPushRspBuilder alloc] init];
}
+ (ApnsPushRspBuilder*) builderWithPrototype:(ApnsPushRsp*) prototype {
  return [[ApnsPushRsp builder] mergeFrom:prototype];
}
- (ApnsPushRspBuilder*) builder {
  return [ApnsPushRsp builder];
}
- (ApnsPushRspBuilder*) toBuilder {
  return [ApnsPushRsp builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"code", NSStringFromResultCode(self.code)];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasCode) {
    [dictionary setObject: @(self.code) forKey: @"code"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ApnsPushRsp class]]) {
    return NO;
  }
  ApnsPushRsp *otherMessage = other;
  return
      self.hasCode == otherMessage.hasCode &&
      (!self.hasCode || self.code == otherMessage.code) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasCode) {
    hashCode = hashCode * 31 + self.code;
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ApnsPushRspBuilder()
@property (strong) ApnsPushRsp* resultApnsPushRsp;
@end

@implementation ApnsPushRspBuilder
@synthesize resultApnsPushRsp;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultApnsPushRsp = [[ApnsPushRsp alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultApnsPushRsp;
}
- (ApnsPushRspBuilder*) clear {
  self.resultApnsPushRsp = [[ApnsPushRsp alloc] init];
  return self;
}
- (ApnsPushRspBuilder*) clone {
  return [ApnsPushRsp builderWithPrototype:resultApnsPushRsp];
}
- (ApnsPushRsp*) defaultInstance {
  return [ApnsPushRsp defaultInstance];
}
- (ApnsPushRsp*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ApnsPushRsp*) buildPartial {
  ApnsPushRsp* returnMe = resultApnsPushRsp;
  self.resultApnsPushRsp = nil;
  return returnMe;
}
- (ApnsPushRspBuilder*) mergeFrom:(ApnsPushRsp*) other {
  if (other == [ApnsPushRsp defaultInstance]) {
    return self;
  }
  if (other.hasCode) {
    [self setCode:other.code];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ApnsPushRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ApnsPushRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        ResultCode value = (ResultCode)[input readEnum];
        if (ResultCodeIsValidValue(value)) {
          [self setCode:value];
        } else {
          [unknownFields mergeVarintField:1 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasCode {
  return resultApnsPushRsp.hasCode;
}
- (ResultCode) code {
  return resultApnsPushRsp.code;
}
- (ApnsPushRspBuilder*) setCode:(ResultCode) value {
  resultApnsPushRsp.hasCode = YES;
  resultApnsPushRsp.code = value;
  return self;
}
- (ApnsPushRspBuilder*) clearCode {
  resultApnsPushRsp.hasCode = NO;
  resultApnsPushRsp.code = ResultCodeNoError;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
